module XTwitterScraper
  module Models
    module X
      module Tweets
        type like_create_response = { success: true }

        class LikeCreateResponse < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor success: true

          def initialize: (?success: true) -> void

          def to_hash: -> { success: true }
        end
      end
    end
  end
end
