module XTwitterScraper
  module Models
    module X
      module Tweets
        type like_create_params =
          { tweet_id: String, account: String }
          & XTwitterScraper::Internal::Type::request_parameters

        class LikeCreateParams < XTwitterScraper::Internal::Type::BaseModel
          extend XTwitterScraper::Internal::Type::RequestParameters::Converter
          include XTwitterScraper::Internal::Type::RequestParameters

          attr_accessor tweet_id: String

          attr_accessor account: String

          def initialize: (
            tweet_id: String,
            account: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> void

          def to_hash: -> {
            tweet_id: String,
            account: String,
            request_options: XTwitterScraper::RequestOptions
          }
        end
      end
    end
  end
end
