module XTwitterScraper
  module Resources
    class X
      class Tweets
        class Like
          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
