module XTwitterScraper
  module Resources
    class X
      class Tweets
        class Retweet
          def create: (
            String id,
            account: String,
            idempotency_key: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Models::X::Tweets::RetweetCreateResponse

          def delete: (
            String id,
            account: String,
            idempotency_key: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Models::X::Tweets::RetweetDeleteResponse

          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
