module XTwitterScraper
  module Resources
    class X
      class Tweets
        class Retweet
          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
