module XTwitterScraper
  module Resources
    class X
      class Users
        class Follow
          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
