module XTwitterScraper
  module Models
    module Support
      type ticket_create_response = { public_id: String }

      class TicketCreateResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_reader public_id: String?

        def public_id=: (String) -> String

        def initialize: (?public_id: String) -> void

        def to_hash: -> { public_id: String }
      end
    end
  end
end
