module XTwitterScraper
  module Models
    module Support
      type ticket_reply_response =
        {
          attachments: ::Array[XTwitterScraper::Models::Support::TicketReplyResponse::Attachment],
          public_id: String
        }

      class TicketReplyResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor attachments: ::Array[XTwitterScraper::Models::Support::TicketReplyResponse::Attachment]

        attr_accessor public_id: String

        def initialize: (
          attachments: ::Array[XTwitterScraper::Models::Support::TicketReplyResponse::Attachment],
          public_id: String
        ) -> void

        def to_hash: -> {
          attachments: ::Array[XTwitterScraper::Models::Support::TicketReplyResponse::Attachment],
          public_id: String
        }

        type attachment =
          {
            public_id: String,
            status: XTwitterScraper::Models::Support::TicketReplyResponse::Attachment::status
          }

        class Attachment < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor public_id: String

          attr_accessor status: XTwitterScraper::Models::Support::TicketReplyResponse::Attachment::status

          def initialize: (
            public_id: String,
            status: XTwitterScraper::Models::Support::TicketReplyResponse::Attachment::status
          ) -> void

          def to_hash: -> {
            public_id: String,
            status: XTwitterScraper::Models::Support::TicketReplyResponse::Attachment::status
          }

          type status = :pending | :ready | :failed

          module Status
            extend XTwitterScraper::Internal::Type::Enum

            PENDING: :pending
            READY: :ready
            FAILED: :failed

            def self?.values: -> ::Array[XTwitterScraper::Models::Support::TicketReplyResponse::Attachment::status]
          end
        end
      end
    end
  end
end
