module XTwitterScraper
  module Resources
    class X
      class Communities
        attr_reader join: XTwitterScraper::Resources::X::Communities::Join

        attr_reader tweets: XTwitterScraper::Resources::X::Communities::Tweets

        def create: (
          account: String,
          name: String,
          idempotency_key: String,
          ?description: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::CommunityCreateResponse

        def delete: (
          String id,
          account: String,
          community_name: String,
          idempotency_key: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::CommunityDeleteResponse

        def retrieve_info: (
          String id,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::CommunityRetrieveInfoResponse

        def retrieve_members: (
          String id,
          ?cursor: String,
          ?page_size: Integer,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_moderators: (
          String id,
          ?cursor: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_search: (
          community_id: String,
          q: String,
          ?cursor: String,
          ?page_size: Integer,
          ?query_type: XTwitterScraper::Models::X::CommunityRetrieveSearchParams::query_type,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
