# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class X
      class Communities
        attr_reader join: XTwitterScraper::Resources::X::Communities::Join

        attr_reader tweets: XTwitterScraper::Resources::X::Communities::Tweets

        def create: (
          account: String,
          name: String,
          idempotency_key: String,
          ?description: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::CommunityCreateResponse

        def delete: (
          String id,
          account: String,
          community_name: String,
          idempotency_key: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::CommunityDeleteResponse

        def retrieve_info: (
          String id,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::CommunityRetrieveInfoResponse

        def retrieve_members: (
          String id,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?page_size: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_moderators: (
          String id,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_search: (
          community_id: String,
          q: String,
          ?cursor: String,
          ?page_size: Integer,
          ?query_type: XTwitterScraper::Models::X::CommunityRetrieveSearchParams::query_type,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
