# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class X
      class Dm
        def retrieve_history: (
          String user_id,
          account: String,
          ?cursor: String,
          ?max_id: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::DmRetrieveHistoryResponse

        def send_: (
          String user_id,
          account: String,
          text: String,
          idempotency_key: String,
          ?media_ids: ::Array[String],
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::DmSendResponse

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
