module XTwitterScraper
  module Resources
    class X
      class Lists
        def retrieve_followers: (
          String id,
          ?cursor: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_members: (
          String id,
          ?cursor: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_tweets: (
          String id,
          ?cursor: String,
          ?include_replies: bool,
          ?since_time: String,
          ?until_time: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
