module XTwitterScraper
  module Resources
    class X
      class Profile
        def update: (
          account: String,
          idempotency_key: String,
          ?description: String,
          ?location: String,
          ?name: String,
          ?url: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::ProfileUpdateResponse

        def update_avatar: (
          account: String,
          url: String,
          idempotency_key: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::ProfileUpdateAvatarResponse

        def update_banner: (
          account: String,
          url: String,
          idempotency_key: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::ProfileUpdateBannerResponse

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
