module XTwitterScraper
  module Resources
    class X
      class Tweets
        attr_reader like: XTwitterScraper::Resources::X::Tweets::Like

        attr_reader retweet: XTwitterScraper::Resources::X::Tweets::Retweet

        def create: (
          account: String,
          ?attachment_url: String,
          ?community_id: String,
          ?is_note_tweet: bool,
          ?media: ::Array[String],
          ?reply_to_tweet_id: String,
          ?text: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::TweetCreateResponse

        def retrieve: (
          String id,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::TweetRetrieveResponse

        def list: (
          ids: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def delete: (
          String id,
          account: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::TweetDeleteResponse

        def get_favoriters: (
          String id,
          ?cursor: String,
          ?page_size: Integer,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def get_quotes: (
          String id,
          ?any_words: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_words: String,
          ?from_user: String,
          ?hashtags: String,
          ?include_replies: bool,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?media_type: XTwitterScraper::Models::X::TweetGetQuotesParams::media_type,
          ?mentioning: String,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::TweetGetQuotesParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::TweetGetQuotesParams::replies,
          ?retweets: XTwitterScraper::Models::X::TweetGetQuotesParams::retweets,
          ?retweets_of_tweet_id: String,
          ?since_date: Date,
          ?since_time: String,
          ?to_user: String,
          ?until_date: Date,
          ?until_time: String,
          ?url: String,
          ?verified_only: bool,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def get_replies: (
          String id,
          ?any_words: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_words: String,
          ?from_user: String,
          ?hashtags: String,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?media_type: XTwitterScraper::Models::X::TweetGetRepliesParams::media_type,
          ?mentioning: String,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::TweetGetRepliesParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::TweetGetRepliesParams::replies,
          ?retweets: XTwitterScraper::Models::X::TweetGetRepliesParams::retweets,
          ?retweets_of_tweet_id: String,
          ?since_date: Date,
          ?since_time: String,
          ?to_user: String,
          ?until_date: Date,
          ?until_time: String,
          ?url: String,
          ?verified_only: bool,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def get_retweeters: (
          String id,
          ?cursor: String,
          ?page_size: Integer,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def get_thread: (
          String id,
          ?cursor: String,
          ?page_size: Integer,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def search: (
          q: String,
          ?advanced_query: String,
          ?any_words: String,
          ?bounding_box: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_words: String,
          ?from_user: String,
          ?hashtags: String,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?limit: Integer,
          ?list_id: String,
          ?media_type: XTwitterScraper::Models::X::TweetSearchParams::media_type,
          ?mentioning: String,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?place: String,
          ?place_country: String,
          ?point_radius: String,
          ?query_type: XTwitterScraper::Models::X::TweetSearchParams::query_type,
          ?quotes: XTwitterScraper::Models::X::TweetSearchParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::TweetSearchParams::replies,
          ?retweets: XTwitterScraper::Models::X::TweetSearchParams::retweets,
          ?retweets_of_tweet_id: String,
          ?since_date: Date,
          ?since_time: String,
          ?to_user: String,
          ?until_date: Date,
          ?until_time: String,
          ?url: String,
          ?verified_only: bool,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
