# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class X
      class Users
        attr_reader follow: XTwitterScraper::Resources::X::Users::Follow

        def retrieve: (
          String id,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::UserProfile

        def remove_follower: (
          String id,
          account: String,
          idempotency_key: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::UserRemoveFollowerResponse

        def retrieve_batch: (
          ids: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::UserRetrieveBatchResponse

        def retrieve_followers: (
          String id,
          ?after: String,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?limit: Integer,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?mode: XTwitterScraper::Models::X::UserRetrieveFollowersParams::mode,
          ?page_size: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::user_retrieve_followers_response

        def retrieve_followers_you_know: (
          String id,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?page_size: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_following: (
          String id,
          ?after: String,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?limit: Integer,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?mode: XTwitterScraper::Models::X::UserRetrieveFollowingParams::mode,
          ?page_size: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::user_retrieve_following_response

        def retrieve_likes: (
          String id,
          ?any_words: String,
          ?blue_verified_only: bool,
          ?card_name: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_source: String,
          ?exclude_words: String,
          ?from_user: String,
          ?geocode: String,
          ?hashtags: String,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?max_faves: Integer,
          ?max_id: String,
          ?max_quotes: Integer,
          ?max_replies: Integer,
          ?max_retweets: Integer,
          ?media_type: XTwitterScraper::Models::X::UserRetrieveLikesParams::media_type,
          ?mentioning: String,
          ?min_bookmarks: Integer,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?min_views: Integer,
          ?native_retweets: bool,
          ?near: String,
          ?news: bool,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::UserRetrieveLikesParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::UserRetrieveLikesParams::replies,
          ?retweets: XTwitterScraper::Models::X::UserRetrieveLikesParams::retweets,
          ?retweets_of_tweet_id: String,
          ?safe: bool,
          ?since_date: Date,
          ?since_id: String,
          ?source: String,
          ?to_user: String,
          ?until_date: Date,
          ?url: String,
          ?verified_only: bool,
          ?within: String,
          ?within_time: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def retrieve_media: (
          String id,
          ?any_words: String,
          ?blue_verified_only: bool,
          ?card_name: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_source: String,
          ?exclude_words: String,
          ?from_user: String,
          ?geocode: String,
          ?hashtags: String,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?max_faves: Integer,
          ?max_id: String,
          ?max_quotes: Integer,
          ?max_replies: Integer,
          ?max_retweets: Integer,
          ?media_type: XTwitterScraper::Models::X::UserRetrieveMediaParams::media_type,
          ?mentioning: String,
          ?min_bookmarks: Integer,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?min_views: Integer,
          ?native_retweets: bool,
          ?near: String,
          ?news: bool,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::UserRetrieveMediaParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::UserRetrieveMediaParams::replies,
          ?retweets: XTwitterScraper::Models::X::UserRetrieveMediaParams::retweets,
          ?retweets_of_tweet_id: String,
          ?safe: bool,
          ?since_date: Date,
          ?since_id: String,
          ?source: String,
          ?to_user: String,
          ?until_date: Date,
          ?url: String,
          ?verified_only: bool,
          ?within: String,
          ?within_time: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def retrieve_mentions: (
          String id,
          ?any_words: String,
          ?blue_verified_only: bool,
          ?card_name: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_source: String,
          ?exclude_words: String,
          ?from_user: String,
          ?geocode: String,
          ?hashtags: String,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?max_faves: Integer,
          ?max_id: String,
          ?max_quotes: Integer,
          ?max_replies: Integer,
          ?max_retweets: Integer,
          ?media_type: XTwitterScraper::Models::X::UserRetrieveMentionsParams::media_type,
          ?mentioning: String,
          ?min_bookmarks: Integer,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?min_views: Integer,
          ?native_retweets: bool,
          ?near: String,
          ?news: bool,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::UserRetrieveMentionsParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::UserRetrieveMentionsParams::replies,
          ?retweets: XTwitterScraper::Models::X::UserRetrieveMentionsParams::retweets,
          ?retweets_of_tweet_id: String,
          ?safe: bool,
          ?since_date: Date,
          ?since_id: String,
          ?since_time: String,
          ?source: String,
          ?to_user: String,
          ?until_date: Date,
          ?until_time: String,
          ?url: String,
          ?verified_only: bool,
          ?within: String,
          ?within_time: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def retrieve_replies: (
          String id,
          ?any_words: String,
          ?blue_verified_only: bool,
          ?card_name: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_source: String,
          ?exclude_words: String,
          ?from_user: String,
          ?geocode: String,
          ?hashtags: String,
          ?include_parent_tweet: bool,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?max_faves: Integer,
          ?max_id: String,
          ?max_quotes: Integer,
          ?max_replies: Integer,
          ?max_retweets: Integer,
          ?media_type: XTwitterScraper::Models::X::UserRetrieveRepliesParams::media_type,
          ?mentioning: String,
          ?min_bookmarks: Integer,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?min_views: Integer,
          ?native_retweets: bool,
          ?near: String,
          ?news: bool,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::UserRetrieveRepliesParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::UserRetrieveRepliesParams::replies,
          ?retweets: XTwitterScraper::Models::X::UserRetrieveRepliesParams::retweets,
          ?retweets_of_tweet_id: String,
          ?safe: bool,
          ?since_date: Date,
          ?since_id: String,
          ?source: String,
          ?to_user: String,
          ?until_date: Date,
          ?url: String,
          ?verified_only: bool,
          ?within: String,
          ?within_time: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def retrieve_search: (
          q: String,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedUsers

        def retrieve_tweets: (
          String id,
          ?any_words: String,
          ?blue_verified_only: bool,
          ?card_name: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_source: String,
          ?exclude_words: String,
          ?from_user: String,
          ?geocode: String,
          ?hashtags: String,
          ?include_parent_tweet: bool,
          ?include_replies: bool,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?max_faves: Integer,
          ?max_id: String,
          ?max_quotes: Integer,
          ?max_replies: Integer,
          ?max_retweets: Integer,
          ?media_type: XTwitterScraper::Models::X::UserRetrieveTweetsParams::media_type,
          ?mentioning: String,
          ?min_bookmarks: Integer,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?min_views: Integer,
          ?native_retweets: bool,
          ?near: String,
          ?news: bool,
          ?page_size: Integer,
          ?quotes: XTwitterScraper::Models::X::UserRetrieveTweetsParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::UserRetrieveTweetsParams::replies,
          ?retweets: XTwitterScraper::Models::X::UserRetrieveTweetsParams::retweets,
          ?retweets_of_tweet_id: String,
          ?safe: bool,
          ?since_date: Date,
          ?since_id: String,
          ?source: String,
          ?to_user: String,
          ?until_date: Date,
          ?url: String,
          ?verified_only: bool,
          ?within: String,
          ?within_time: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::PaginatedTweets

        def retrieve_verified_followers: (
          String id,
          ?after: String,
          ?bio_contains: String,
          ?cursor: String,
          ?has_location: bool,
          ?has_website: bool,
          ?limit: Integer,
          ?location_contains: String,
          ?max_followers: Integer,
          ?max_following: Integer,
          ?max_statuses: Integer,
          ?min_account_age_days: Integer,
          ?min_followers: Integer,
          ?min_following: Integer,
          ?min_statuses: Integer,
          ?mode: XTwitterScraper::Models::X::UserRetrieveVerifiedFollowersParams::mode,
          ?page_size: Integer,
          ?username_contains: String,
          ?verified_only: bool,
          ?verified_type: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> XTwitterScraper::Models::X::user_retrieve_verified_followers_response

        def initialize: (client: XTwitterScraper::Client) -> void
      end
    end
  end
end
