module XTwitterScraper
  module Models
    module Bot
      type platform_link_create_response =
        {
          id: String,
          created_at: Time,
          platform: String,
          platform_user_id: String
        }

      class PlatformLinkCreateResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor platform: String

        attr_accessor platform_user_id: String

        def initialize: (
          id: String,
          created_at: Time,
          platform: String,
          platform_user_id: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          platform: String,
          platform_user_id: String
        }
      end
    end
  end
end
