module XTwitterScraper
  module Models
    module Bot
      type platform_link_delete_params =
        {
          platform: XTwitterScraper::Models::Bot::PlatformLinkDeleteParams::platform,
          platform_user_id: String
        }
        & XTwitterScraper::Internal::Type::request_parameters

      class PlatformLinkDeleteParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor platform: XTwitterScraper::Models::Bot::PlatformLinkDeleteParams::platform

        attr_accessor platform_user_id: String

        def initialize: (
          platform: XTwitterScraper::Models::Bot::PlatformLinkDeleteParams::platform,
          platform_user_id: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          platform: XTwitterScraper::Models::Bot::PlatformLinkDeleteParams::platform,
          platform_user_id: String,
          request_options: XTwitterScraper::RequestOptions
        }

        type platform = :telegram

        module Platform
          extend XTwitterScraper::Internal::Type::Enum

          TELEGRAM: :telegram

          def self?.values: -> ::Array[XTwitterScraper::Models::Bot::PlatformLinkDeleteParams::platform]
        end
      end
    end
  end
end
