module XTwitterScraper
  class AccountRetrieveParams = XTwitterScraper::Models::AccountRetrieveParams

  class AccountSetXUsernameParams = XTwitterScraper::Models::AccountSetXUsernameParams

  class AccountUpdateLocaleParams = XTwitterScraper::Models::AccountUpdateLocaleParams

  class APIKey = XTwitterScraper::Models::APIKey

  class APIKeyCreateParams = XTwitterScraper::Models::APIKeyCreateParams

  class APIKeyListParams = XTwitterScraper::Models::APIKeyListParams

  class APIKeyRevokeParams = XTwitterScraper::Models::APIKeyRevokeParams

  class ComposeCreateParams = XTwitterScraper::Models::ComposeCreateParams

  class CreditRetrieveBalanceParams = XTwitterScraper::Models::CreditRetrieveBalanceParams

  class CreditTopupBalanceParams = XTwitterScraper::Models::CreditTopupBalanceParams

  class Delivery = XTwitterScraper::Models::Delivery

  class Draft = XTwitterScraper::Models::Draft

  class DraftCreateParams = XTwitterScraper::Models::DraftCreateParams

  class DraftDeleteParams = XTwitterScraper::Models::DraftDeleteParams

  class DraftDetail = XTwitterScraper::Models::DraftDetail

  class DraftListParams = XTwitterScraper::Models::DraftListParams

  class DraftRetrieveParams = XTwitterScraper::Models::DraftRetrieveParams

  class DrawDetail = XTwitterScraper::Models::DrawDetail

  class DrawExportParams = XTwitterScraper::Models::DrawExportParams

  class DrawListItem = XTwitterScraper::Models::DrawListItem

  class DrawListParams = XTwitterScraper::Models::DrawListParams

  class DrawRetrieveParams = XTwitterScraper::Models::DrawRetrieveParams

  class DrawRunParams = XTwitterScraper::Models::DrawRunParams

  class Error = XTwitterScraper::Models::Error

  class Event = XTwitterScraper::Models::Event

  class EventDetail = XTwitterScraper::Models::EventDetail

  class EventListParams = XTwitterScraper::Models::EventListParams

  class EventRetrieveParams = XTwitterScraper::Models::EventRetrieveParams

  module EventType = XTwitterScraper::Models::EventType

  class ExtractionEstimateCostParams = XTwitterScraper::Models::ExtractionEstimateCostParams

  class ExtractionExportResultsParams = XTwitterScraper::Models::ExtractionExportResultsParams

  class ExtractionJob = XTwitterScraper::Models::ExtractionJob

  class ExtractionListParams = XTwitterScraper::Models::ExtractionListParams

  class ExtractionRetrieveParams = XTwitterScraper::Models::ExtractionRetrieveParams

  class ExtractionRunParams = XTwitterScraper::Models::ExtractionRunParams

  class Integration = XTwitterScraper::Models::Integration

  class IntegrationCreateParams = XTwitterScraper::Models::IntegrationCreateParams

  class IntegrationDeleteParams = XTwitterScraper::Models::IntegrationDeleteParams

  class IntegrationDelivery = XTwitterScraper::Models::IntegrationDelivery

  class IntegrationListDeliveriesParams = XTwitterScraper::Models::IntegrationListDeliveriesParams

  class IntegrationListParams = XTwitterScraper::Models::IntegrationListParams

  class IntegrationRetrieveParams = XTwitterScraper::Models::IntegrationRetrieveParams

  class IntegrationSendTestParams = XTwitterScraper::Models::IntegrationSendTestParams

  class IntegrationUpdateParams = XTwitterScraper::Models::IntegrationUpdateParams

  class Monitor = XTwitterScraper::Models::Monitor

  class MonitorCreateParams = XTwitterScraper::Models::MonitorCreateParams

  class MonitorDeactivateParams = XTwitterScraper::Models::MonitorDeactivateParams

  class MonitorListParams = XTwitterScraper::Models::MonitorListParams

  class MonitorRetrieveParams = XTwitterScraper::Models::MonitorRetrieveParams

  class MonitorUpdateParams = XTwitterScraper::Models::MonitorUpdateParams

  class PaginatedTweets = XTwitterScraper::Models::PaginatedTweets

  class PaginatedUsers = XTwitterScraper::Models::PaginatedUsers

  class RadarItem = XTwitterScraper::Models::RadarItem

  class RadarRetrieveTrendingTopicsParams = XTwitterScraper::Models::RadarRetrieveTrendingTopicsParams

  class StyleAnalyzeParams = XTwitterScraper::Models::StyleAnalyzeParams

  class StyleCompareParams = XTwitterScraper::Models::StyleCompareParams

  class StyleDeleteParams = XTwitterScraper::Models::StyleDeleteParams

  class StyleGetPerformanceParams = XTwitterScraper::Models::StyleGetPerformanceParams

  class StyleListParams = XTwitterScraper::Models::StyleListParams

  class StyleProfile = XTwitterScraper::Models::StyleProfile

  class StyleProfileSummary = XTwitterScraper::Models::StyleProfileSummary

  class StyleRetrieveParams = XTwitterScraper::Models::StyleRetrieveParams

  class StyleUpdateParams = XTwitterScraper::Models::StyleUpdateParams

  class SubscribeCreateParams = XTwitterScraper::Models::SubscribeCreateParams

  module Support = XTwitterScraper::Models::Support

  class TrendListParams = XTwitterScraper::Models::TrendListParams

  class Webhook = XTwitterScraper::Models::Webhook

  class WebhookCreateParams = XTwitterScraper::Models::WebhookCreateParams

  class WebhookDeactivateParams = XTwitterScraper::Models::WebhookDeactivateParams

  class WebhookListDeliveriesParams = XTwitterScraper::Models::WebhookListDeliveriesParams

  class WebhookListParams = XTwitterScraper::Models::WebhookListParams

  class WebhookTestParams = XTwitterScraper::Models::WebhookTestParams

  class WebhookUpdateParams = XTwitterScraper::Models::WebhookUpdateParams

  class Winner = XTwitterScraper::Models::Winner

  module X = XTwitterScraper::Models::X

  class XGetArticleParams = XTwitterScraper::Models::XGetArticleParams

  class XGetHomeTimelineParams = XTwitterScraper::Models::XGetHomeTimelineParams

  class XGetNotificationsParams = XTwitterScraper::Models::XGetNotificationsParams

  class XGetTrendsParams = XTwitterScraper::Models::XGetTrendsParams
end
