# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module Monitors
      type keyword_deactivate_response = { success: true }

      class KeywordDeactivateResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor success: true

        def initialize: (?success: true) -> void

        def to_hash: -> { success: true }
      end
    end
  end
end
