module XTwitterScraper
  module Internal
    class CursorPageLegacy[Elem]
      include XTwitterScraper::Internal::Type::BasePage[Elem]

      attr_accessor items: ::Array[Elem]?

      attr_accessor next_cursor: String

      attr_accessor has_more: bool

      def inspect: -> String
    end
  end
end
