module XTwitterScraper
  module Internal
    class CursorPage[Elem]
      include XTwitterScraper::Internal::Type::BasePage[Elem]

      attr_accessor tweets: ::Array[top]

      attr_accessor users: ::Array[top]

      attr_accessor next_cursor: String

      attr_accessor has_next_page: bool

      def inspect: -> String
    end
  end
end
