module XTwitterScraper
  module Internal
    class CursorPage[Elem]
      include XTwitterScraper::Internal::Type::BasePage[Elem]

      attr_accessor next_cursor: String?

      attr_accessor has_next_page: bool

      def inspect: -> String
    end
  end
end
