module XTwitterScraper
  module Resources
    class X
      class Communities
        class Join
          def create: (
            String id,
            account: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::X::CommunityActionResult

          def delete_all: (
            String id,
            account: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::X::CommunityActionResult

          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
