# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class X
      class Communities
        class Join
          def create: (
            String id,
            account: String,
            idempotency_key: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Models::X::Communities::JoinCreateResponse

          def delete_all: (
            String id,
            account: String,
            idempotency_key: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Models::X::Communities::JoinDeleteAllResponse

          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
