module XTwitterScraper
  module Resources
    class X
      class Communities
        class Tweets
          def list: (
            q: String,
            ?cursor: String,
            ?query_type: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Internal::CursorPage[XTwitterScraper::PaginatedTweets]

          def list_by_community: (
            String id,
            ?cursor: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Internal::CursorPage[XTwitterScraper::PaginatedTweets]

          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
