module XTwitterScraper
  module Resources
    class X
      class Communities
        class Tweets
          def list: (
            q: String,
            ?cursor: String,
            ?query_type: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> XTwitterScraper::Models::X::Communities::TweetListResponse

          def initialize: (client: XTwitterScraper::Client) -> void
        end
      end
    end
  end
end
