module XTwitterScraper
  module Models
    module X
      type account_connection_attempt_retrieve_response =
        XTwitterScraper::Models::X::AccountConnectionAttemptRetrieveResponse::Pending
        | XTwitterScraper::Models::X::AccountConnectionAttemptRetrieveResponse::Success
        | XTwitterScraper::Models::X::AccountConnectionAttemptRetrieveResponse::Failed
        | XTwitterScraper::Models::X::AccountConnectionAttemptRetrieveResponse::RequiresEmailCode

      module AccountConnectionAttemptRetrieveResponse
        extend XTwitterScraper::Internal::Type::Union

        type pending =
          {
            id: String,
            object: :x_account_connection_attempt,
            poll_after_ms: Integer,
            status: :pending
          }

        class Pending < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor object: :x_account_connection_attempt

          attr_accessor poll_after_ms: Integer

          attr_accessor status: :pending

          def initialize: (
            id: String,
            poll_after_ms: Integer,
            ?object: :x_account_connection_attempt,
            ?status: :pending
          ) -> void

          def to_hash: -> {
            id: String,
            object: :x_account_connection_attempt,
            poll_after_ms: Integer,
            status: :pending
          }

          module Object
            X_ACCOUNT_CONNECTION_ATTEMPT: :x_account_connection_attempt
          end

          module Status
            PENDING: :pending
          end
        end

        type success =
          {
            id: String,
            object: :x_account_connection_attempt,
            status: :success
          }

        class Success < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor object: :x_account_connection_attempt

          attr_accessor status: :success

          def initialize: (
            id: String,
            ?object: :x_account_connection_attempt,
            ?status: :success
          ) -> void

          def to_hash: -> {
            id: String,
            object: :x_account_connection_attempt,
            status: :success
          }

          module Object
            X_ACCOUNT_CONNECTION_ATTEMPT: :x_account_connection_attempt
          end

          module Status
            SUCCESS: :success
          end
        end

        type failed =
          {
            id: String,
            error: String,
            object: :x_account_connection_attempt,
            retryable: bool,
            status: :failed,
            reason: String
          }

        class Failed < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor error: String

          attr_accessor object: :x_account_connection_attempt

          attr_accessor retryable: bool

          attr_accessor status: :failed

          attr_reader reason: String?

          def reason=: (String) -> String

          def initialize: (
            id: String,
            error: String,
            retryable: bool,
            ?reason: String,
            ?object: :x_account_connection_attempt,
            ?status: :failed
          ) -> void

          def to_hash: -> {
            id: String,
            error: String,
            object: :x_account_connection_attempt,
            retryable: bool,
            status: :failed,
            reason: String
          }

          module Object
            X_ACCOUNT_CONNECTION_ATTEMPT: :x_account_connection_attempt
          end

          module Status
            FAILED: :failed
          end
        end

        type requires_email_code =
          {
            id: String,
            expires_at: Time,
            message: String,
            object: :x_account_connection_challenge,
            status: :requires_email_code,
            username: String
          }

        class RequiresEmailCode < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor expires_at: Time

          attr_accessor message: String

          attr_accessor object: :x_account_connection_challenge

          attr_accessor status: :requires_email_code

          attr_accessor username: String

          def initialize: (
            id: String,
            expires_at: Time,
            message: String,
            username: String,
            ?object: :x_account_connection_challenge,
            ?status: :requires_email_code
          ) -> void

          def to_hash: -> {
            id: String,
            expires_at: Time,
            message: String,
            object: :x_account_connection_challenge,
            status: :requires_email_code,
            username: String
          }

          module Object
            X_ACCOUNT_CONNECTION_CHALLENGE: :x_account_connection_challenge
          end

          module Status
            REQUIRES_EMAIL_CODE: :requires_email_code
          end
        end

        XAccountConnectionAttemptPending: singleton(Pending)
        XAccountConnectionAttemptSuccess: singleton(Success)
        XAccountConnectionAttemptFailed: singleton(Failed)
        XAccountConnectionChallenge: singleton(RequiresEmailCode)

        def self?.variants: -> ::Array[XTwitterScraper::Models::X::account_connection_attempt_retrieve_response]
      end
    end
  end
end
