# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type account_connection_challenge_submit_params =
        { id: String, email_code: String }
        & XTwitterScraper::Internal::Type::request_parameters

      class AccountConnectionChallengeSubmitParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor email_code: String

        def initialize: (
          id: String,
          email_code: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          email_code: String,
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
