# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type account_connection_challenge_submit_response =
        {
          id: String,
          created_at: Time,
          health: XTwitterScraper::Models::X::AccountConnectionChallengeSubmitResponse::health,
          status: String,
          x_user_id: String,
          x_username: String
        }

      class AccountConnectionChallengeSubmitResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor health: XTwitterScraper::Models::X::AccountConnectionChallengeSubmitResponse::health

        attr_accessor status: String

        attr_accessor x_user_id: String

        attr_accessor x_username: String

        def initialize: (
          id: String,
          created_at: Time,
          health: XTwitterScraper::Models::X::AccountConnectionChallengeSubmitResponse::health,
          status: String,
          x_user_id: String,
          x_username: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          health: XTwitterScraper::Models::X::AccountConnectionChallengeSubmitResponse::health,
          status: String,
          x_user_id: String,
          x_username: String
        }

        type health =
          :healthy
          | :locked
          | :needsReauth
          | :recovering
          | :suspended
          | :temporaryIssue

        module Health
          extend XTwitterScraper::Internal::Type::Enum

          HEALTHY: :healthy
          LOCKED: :locked
          NEEDS_REAUTH: :needsReauth
          RECOVERING: :recovering
          SUSPENDED: :suspended
          TEMPORARY_ISSUE: :temporaryIssue

          def self?.values: -> ::Array[XTwitterScraper::Models::X::AccountConnectionChallengeSubmitResponse::health]
        end
      end
    end
  end
end
