# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      AccountCreateResponse: XTwitterScraper::Internal::Type::Converter
    end
  end
end
