# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type account_list_response =
        { accounts: ::Array[XTwitterScraper::X::XAccount] }

      class AccountListResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor accounts: ::Array[XTwitterScraper::X::XAccount]

        def initialize: (
          accounts: ::Array[XTwitterScraper::X::XAccount]
        ) -> void

        def to_hash: -> { accounts: ::Array[XTwitterScraper::X::XAccount] }
      end
    end
  end
end
