# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type dm_retrieve_history_params =
        { user_id: String, account: String, cursor: String, max_id: String }
        & XTwitterScraper::Internal::Type::request_parameters

      class DmRetrieveHistoryParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor user_id: String

        attr_accessor account: String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader max_id: String?

        def max_id=: (String) -> String

        def initialize: (
          user_id: String,
          account: String,
          ?cursor: String,
          ?max_id: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          account: String,
          cursor: String,
          max_id: String,
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
