# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type dm_send_params =
        {
          user_id: String,
          account: String,
          text: String,
          idempotency_key: String,
          media_ids: ::Array[String]
        }
        & XTwitterScraper::Internal::Type::request_parameters

      class DmSendParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor user_id: String

        attr_accessor account: String

        attr_accessor text: String

        attr_accessor idempotency_key: String

        attr_reader media_ids: ::Array[String]?

        def media_ids=: (::Array[String]) -> ::Array[String]

        def initialize: (
          user_id: String,
          account: String,
          text: String,
          idempotency_key: String,
          ?media_ids: ::Array[String],
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          account: String,
          text: String,
          idempotency_key: String,
          media_ids: ::Array[String],
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
