module XTwitterScraper
  module Models
    module X
      type profile_update_banner_response = { success: true }

      class ProfileUpdateBannerResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor success: true

        def initialize: (?success: true) -> void

        def to_hash: -> { success: true }
      end
    end
  end
end
