module XTwitterScraper
  module Models
    module X
      type profile_update_banner_params =
        { account: String, file: XTwitterScraper::Internal::file_input }
        & XTwitterScraper::Internal::Type::request_parameters

      class ProfileUpdateBannerParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor file: XTwitterScraper::Internal::file_input

        def initialize: (
          account: String,
          file: XTwitterScraper::Internal::file_input,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          file: XTwitterScraper::Internal::file_input,
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
