# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type tweet_author = ::Hash[Symbol, top]

      class TweetAuthor < XTwitterScraper::Models::UserProfile
        def followers: -> Integer

        def followers=: (Integer _) -> Integer

        def verified: -> bool

        def verified=: (bool _) -> bool

        def initialize: (**untyped) -> void

        def to_hash: -> ::Hash[Symbol, top]
      end
    end
  end
end
