# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type tweet_create_params =
        {
          account: String,
          idempotency_key: String,
          community_id: String,
          is_note_tweet: bool,
          media: ::Array[String],
          reply_to_tweet_id: String,
          text: String
        }
        & XTwitterScraper::Internal::Type::request_parameters

      class TweetCreateParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor idempotency_key: String

        attr_reader community_id: String?

        def community_id=: (String) -> String

        attr_reader is_note_tweet: bool?

        def is_note_tweet=: (bool) -> bool

        attr_reader media: ::Array[String]?

        def media=: (::Array[String]) -> ::Array[String]

        attr_reader reply_to_tweet_id: String?

        def reply_to_tweet_id=: (String) -> String

        attr_reader text: String?

        def text=: (String) -> String

        def initialize: (
          account: String,
          idempotency_key: String,
          ?community_id: String,
          ?is_note_tweet: bool,
          ?media: ::Array[String],
          ?reply_to_tweet_id: String,
          ?text: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          idempotency_key: String,
          community_id: String,
          is_note_tweet: bool,
          media: ::Array[String],
          reply_to_tweet_id: String,
          text: String,
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
