module XTwitterScraper
  module Models
    module X
      type tweet_get_quotes_response =
        {
          has_next_page: bool,
          next_cursor: String,
          tweets: ::Array[XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet]
        }

      class TweetGetQuotesResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor has_next_page: bool

        attr_accessor next_cursor: String

        attr_accessor tweets: ::Array[XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet]

        def initialize: (
          has_next_page: bool,
          next_cursor: String,
          tweets: ::Array[XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet]
        ) -> void

        def to_hash: -> {
          has_next_page: bool,
          next_cursor: String,
          tweets: ::Array[XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet]
        }

        type tweet =
          {
            id: String,
            text: String,
            author: XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet::Author,
            bookmark_count: Integer,
            created_at: String,
            is_note_tweet: bool,
            like_count: Integer,
            quote_count: Integer,
            reply_count: Integer,
            retweet_count: Integer,
            view_count: Integer
          }

        class Tweet < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor text: String

          attr_reader author: XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet::Author?

          def author=: (
            XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet::Author
          ) -> XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet::Author

          attr_reader bookmark_count: Integer?

          def bookmark_count=: (Integer) -> Integer

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader is_note_tweet: bool?

          def is_note_tweet=: (bool) -> bool

          attr_reader like_count: Integer?

          def like_count=: (Integer) -> Integer

          attr_reader quote_count: Integer?

          def quote_count=: (Integer) -> Integer

          attr_reader reply_count: Integer?

          def reply_count=: (Integer) -> Integer

          attr_reader retweet_count: Integer?

          def retweet_count=: (Integer) -> Integer

          attr_reader view_count: Integer?

          def view_count=: (Integer) -> Integer

          def initialize: (
            id: String,
            text: String,
            ?author: XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet::Author,
            ?bookmark_count: Integer,
            ?created_at: String,
            ?is_note_tweet: bool,
            ?like_count: Integer,
            ?quote_count: Integer,
            ?reply_count: Integer,
            ?retweet_count: Integer,
            ?view_count: Integer
          ) -> void

          def to_hash: -> {
            id: String,
            text: String,
            author: XTwitterScraper::Models::X::TweetGetQuotesResponse::Tweet::Author,
            bookmark_count: Integer,
            created_at: String,
            is_note_tweet: bool,
            like_count: Integer,
            quote_count: Integer,
            reply_count: Integer,
            retweet_count: Integer,
            view_count: Integer
          }

          type author =
            { id: String, name: String, username: String, verified: bool }

          class Author < XTwitterScraper::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor name: String

            attr_accessor username: String

            attr_reader verified: bool?

            def verified=: (bool) -> bool

            def initialize: (
              id: String,
              name: String,
              username: String,
              ?verified: bool
            ) -> void

            def to_hash: -> {
              id: String,
              name: String,
              username: String,
              verified: bool
            }
          end
        end
      end
    end
  end
end
