# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type tweet_detail =
        {
          id: String,
          bookmark_count: Integer,
          like_count: Integer,
          quote_count: Integer,
          reply_count: Integer,
          retweet_count: Integer,
          text: String,
          view_count: Integer,
          article: XTwitterScraper::X::TweetDetail::Article,
          author: XTwitterScraper::X::TweetAuthor,
          card: XTwitterScraper::X::TweetDetail::Card,
          community_note: XTwitterScraper::X::TweetDetail::CommunityNote,
          content_disclosure: XTwitterScraper::ContentDisclosure,
          conversation_id: String,
          created_at: String,
          display_text_range: ::Array[Integer],
          edit: XTwitterScraper::X::TweetDetail::Edit,
          entities: ::Hash[Symbol, top],
          in_reply_to_id: String,
          in_reply_to_user_id: String,
          in_reply_to_username: String,
          is_limited_reply: bool,
          is_note_tweet: bool,
          is_quote_status: bool,
          is_reply: bool,
          is_translatable: bool,
          lang: String,
          media: ::Array[XTwitterScraper::TweetMedia],
          note_tweet: XTwitterScraper::X::TweetDetail::NoteTweet,
          place: XTwitterScraper::X::TweetDetail::Place,
          possibly_sensitive: bool,
          previous_counts: XTwitterScraper::X::TweetDetail::PreviousCounts,
          quoted_tweet: XTwitterScraper::EmbeddedTweet,
          retweeted_tweet: XTwitterScraper::EmbeddedTweet,
          source: String,
          type: String,
          url: String,
          view_state: String
        }

      class TweetDetail < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor bookmark_count: Integer

        attr_accessor like_count: Integer

        attr_accessor quote_count: Integer

        attr_accessor reply_count: Integer

        attr_accessor retweet_count: Integer

        attr_accessor text: String

        attr_accessor view_count: Integer

        attr_reader article: XTwitterScraper::X::TweetDetail::Article?

        def article=: (
          XTwitterScraper::X::TweetDetail::Article
        ) -> XTwitterScraper::X::TweetDetail::Article

        attr_reader author: XTwitterScraper::X::TweetAuthor?

        def author=: (
          XTwitterScraper::X::TweetAuthor
        ) -> XTwitterScraper::X::TweetAuthor

        attr_reader card: XTwitterScraper::X::TweetDetail::Card?

        def card=: (
          XTwitterScraper::X::TweetDetail::Card
        ) -> XTwitterScraper::X::TweetDetail::Card

        attr_reader community_note: XTwitterScraper::X::TweetDetail::CommunityNote?

        def community_note=: (
          XTwitterScraper::X::TweetDetail::CommunityNote
        ) -> XTwitterScraper::X::TweetDetail::CommunityNote

        attr_reader content_disclosure: XTwitterScraper::ContentDisclosure?

        def content_disclosure=: (
          XTwitterScraper::ContentDisclosure
        ) -> XTwitterScraper::ContentDisclosure

        attr_reader conversation_id: String?

        def conversation_id=: (String) -> String

        attr_reader created_at: String?

        def created_at=: (String) -> String

        attr_reader display_text_range: ::Array[Integer]?

        def display_text_range=: (::Array[Integer]) -> ::Array[Integer]

        attr_reader edit: XTwitterScraper::X::TweetDetail::Edit?

        def edit=: (
          XTwitterScraper::X::TweetDetail::Edit
        ) -> XTwitterScraper::X::TweetDetail::Edit

        attr_reader entities: ::Hash[Symbol, top]?

        def entities=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader in_reply_to_id: String?

        def in_reply_to_id=: (String) -> String

        attr_reader in_reply_to_user_id: String?

        def in_reply_to_user_id=: (String) -> String

        attr_reader in_reply_to_username: String?

        def in_reply_to_username=: (String) -> String

        attr_reader is_limited_reply: bool?

        def is_limited_reply=: (bool) -> bool

        attr_reader is_note_tweet: bool?

        def is_note_tweet=: (bool) -> bool

        attr_reader is_quote_status: bool?

        def is_quote_status=: (bool) -> bool

        attr_reader is_reply: bool?

        def is_reply=: (bool) -> bool

        attr_reader is_translatable: bool?

        def is_translatable=: (bool) -> bool

        attr_reader lang: String?

        def lang=: (String) -> String

        attr_reader media: ::Array[XTwitterScraper::TweetMedia]?

        def media=: (
          ::Array[XTwitterScraper::TweetMedia]
        ) -> ::Array[XTwitterScraper::TweetMedia]

        attr_reader note_tweet: XTwitterScraper::X::TweetDetail::NoteTweet?

        def note_tweet=: (
          XTwitterScraper::X::TweetDetail::NoteTweet
        ) -> XTwitterScraper::X::TweetDetail::NoteTweet

        attr_reader place: XTwitterScraper::X::TweetDetail::Place?

        def place=: (
          XTwitterScraper::X::TweetDetail::Place
        ) -> XTwitterScraper::X::TweetDetail::Place

        attr_reader possibly_sensitive: bool?

        def possibly_sensitive=: (bool) -> bool

        attr_reader previous_counts: XTwitterScraper::X::TweetDetail::PreviousCounts?

        def previous_counts=: (
          XTwitterScraper::X::TweetDetail::PreviousCounts
        ) -> XTwitterScraper::X::TweetDetail::PreviousCounts

        attr_reader quoted_tweet: XTwitterScraper::EmbeddedTweet?

        def quoted_tweet=: (
          XTwitterScraper::EmbeddedTweet
        ) -> XTwitterScraper::EmbeddedTweet

        attr_reader retweeted_tweet: XTwitterScraper::EmbeddedTweet?

        def retweeted_tweet=: (
          XTwitterScraper::EmbeddedTweet
        ) -> XTwitterScraper::EmbeddedTweet

        attr_reader source: String?

        def source=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        attr_reader url: String?

        def url=: (String) -> String

        attr_reader view_state: String?

        def view_state=: (String) -> String

        def initialize: (
          id: String,
          bookmark_count: Integer,
          like_count: Integer,
          quote_count: Integer,
          reply_count: Integer,
          retweet_count: Integer,
          text: String,
          view_count: Integer,
          ?article: XTwitterScraper::X::TweetDetail::Article,
          ?author: XTwitterScraper::X::TweetAuthor,
          ?card: XTwitterScraper::X::TweetDetail::Card,
          ?community_note: XTwitterScraper::X::TweetDetail::CommunityNote,
          ?content_disclosure: XTwitterScraper::ContentDisclosure,
          ?conversation_id: String,
          ?created_at: String,
          ?display_text_range: ::Array[Integer],
          ?edit: XTwitterScraper::X::TweetDetail::Edit,
          ?entities: ::Hash[Symbol, top],
          ?in_reply_to_id: String,
          ?in_reply_to_user_id: String,
          ?in_reply_to_username: String,
          ?is_limited_reply: bool,
          ?is_note_tweet: bool,
          ?is_quote_status: bool,
          ?is_reply: bool,
          ?is_translatable: bool,
          ?lang: String,
          ?media: ::Array[XTwitterScraper::TweetMedia],
          ?note_tweet: XTwitterScraper::X::TweetDetail::NoteTweet,
          ?place: XTwitterScraper::X::TweetDetail::Place,
          ?possibly_sensitive: bool,
          ?previous_counts: XTwitterScraper::X::TweetDetail::PreviousCounts,
          ?quoted_tweet: XTwitterScraper::EmbeddedTweet,
          ?retweeted_tweet: XTwitterScraper::EmbeddedTweet,
          ?source: String,
          ?type: String,
          ?url: String,
          ?view_state: String
        ) -> void

        def to_hash: -> {
          id: String,
          bookmark_count: Integer,
          like_count: Integer,
          quote_count: Integer,
          reply_count: Integer,
          retweet_count: Integer,
          text: String,
          view_count: Integer,
          article: XTwitterScraper::X::TweetDetail::Article,
          author: XTwitterScraper::X::TweetAuthor,
          card: XTwitterScraper::X::TweetDetail::Card,
          community_note: XTwitterScraper::X::TweetDetail::CommunityNote,
          content_disclosure: XTwitterScraper::ContentDisclosure,
          conversation_id: String,
          created_at: String,
          display_text_range: ::Array[Integer],
          edit: XTwitterScraper::X::TweetDetail::Edit,
          entities: ::Hash[Symbol, top],
          in_reply_to_id: String,
          in_reply_to_user_id: String,
          in_reply_to_username: String,
          is_limited_reply: bool,
          is_note_tweet: bool,
          is_quote_status: bool,
          is_reply: bool,
          is_translatable: bool,
          lang: String,
          media: ::Array[XTwitterScraper::TweetMedia],
          note_tweet: XTwitterScraper::X::TweetDetail::NoteTweet,
          place: XTwitterScraper::X::TweetDetail::Place,
          possibly_sensitive: bool,
          previous_counts: XTwitterScraper::X::TweetDetail::PreviousCounts,
          quoted_tweet: XTwitterScraper::EmbeddedTweet,
          retweeted_tweet: XTwitterScraper::EmbeddedTweet,
          source: String,
          type: String,
          url: String,
          view_state: String
        }

        type article =
          {
            id: String,
            cover_media_url: String,
            preview_text: String,
            title: String
          }

        class Article < XTwitterScraper::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader cover_media_url: String?

          def cover_media_url=: (String) -> String

          attr_reader preview_text: String?

          def preview_text=: (String) -> String

          attr_reader title: String?

          def title=: (String) -> String

          def initialize: (
            ?id: String,
            ?cover_media_url: String,
            ?preview_text: String,
            ?title: String
          ) -> void

          def to_hash: -> {
            id: String,
            cover_media_url: String,
            preview_text: String,
            title: String
          }
        end

        type card =
          {
            id: String,
            binding_values: ::Hash[Symbol, top],
            name: String,
            url: String
          }

        class Card < XTwitterScraper::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader binding_values: ::Hash[Symbol, top]?

          def binding_values=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader url: String?

          def url=: (String) -> String

          def initialize: (
            ?id: String,
            ?binding_values: ::Hash[Symbol, top],
            ?name: String,
            ?url: String
          ) -> void

          def to_hash: -> {
            id: String,
            binding_values: ::Hash[Symbol, top],
            name: String,
            url: String
          }
        end

        type community_note =
          {
            id: String,
            destination_url: String,
            footer: String,
            short_title: String,
            subtitle: String,
            title: String,
            visual_style: String
          }

        class CommunityNote < XTwitterScraper::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader destination_url: String?

          def destination_url=: (String) -> String

          attr_reader footer: String?

          def footer=: (String) -> String

          attr_reader short_title: String?

          def short_title=: (String) -> String

          attr_reader subtitle: String?

          def subtitle=: (String) -> String

          attr_reader title: String?

          def title=: (String) -> String

          attr_reader visual_style: String?

          def visual_style=: (String) -> String

          def initialize: (
            ?id: String,
            ?destination_url: String,
            ?footer: String,
            ?short_title: String,
            ?subtitle: String,
            ?title: String,
            ?visual_style: String
          ) -> void

          def to_hash: -> {
            id: String,
            destination_url: String,
            footer: String,
            short_title: String,
            subtitle: String,
            title: String,
            visual_style: String
          }
        end

        type edit =
          { editable_until_msecs: String, edit_tweet_ids: ::Array[String] }

        class Edit < XTwitterScraper::Internal::Type::BaseModel
          attr_reader editable_until_msecs: String?

          def editable_until_msecs=: (String) -> String

          attr_reader edit_tweet_ids: ::Array[String]?

          def edit_tweet_ids=: (::Array[String]) -> ::Array[String]

          def initialize: (
            ?editable_until_msecs: String,
            ?edit_tweet_ids: ::Array[String]
          ) -> void

          def to_hash: -> {
            editable_until_msecs: String,
            edit_tweet_ids: ::Array[String]
          }
        end

        type note_tweet =
          {
            text: String,
            id: String,
            entities: ::Hash[Symbol, top],
            is_expandable: bool,
            richtext_tags: ::Array[XTwitterScraper::X::TweetDetail::NoteTweet::RichtextTag]
          }

        class NoteTweet < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor text: String

          attr_reader id: String?

          def id=: (String) -> String

          attr_reader entities: ::Hash[Symbol, top]?

          def entities=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader is_expandable: bool?

          def is_expandable=: (bool) -> bool

          attr_reader richtext_tags: ::Array[XTwitterScraper::X::TweetDetail::NoteTweet::RichtextTag]?

          def richtext_tags=: (
            ::Array[XTwitterScraper::X::TweetDetail::NoteTweet::RichtextTag]
          ) -> ::Array[XTwitterScraper::X::TweetDetail::NoteTweet::RichtextTag]

          def initialize: (
            text: String,
            ?id: String,
            ?entities: ::Hash[Symbol, top],
            ?is_expandable: bool,
            ?richtext_tags: ::Array[XTwitterScraper::X::TweetDetail::NoteTweet::RichtextTag]
          ) -> void

          def to_hash: -> {
            text: String,
            id: String,
            entities: ::Hash[Symbol, top],
            is_expandable: bool,
            richtext_tags: ::Array[XTwitterScraper::X::TweetDetail::NoteTweet::RichtextTag]
          }

          type richtext_tag =
            { from_index: Integer, to_index: Integer, types: ::Array[String] }

          class RichtextTag < XTwitterScraper::Internal::Type::BaseModel
            attr_accessor from_index: Integer

            attr_accessor to_index: Integer

            attr_accessor types: ::Array[String]

            def initialize: (
              from_index: Integer,
              to_index: Integer,
              types: ::Array[String]
            ) -> void

            def to_hash: -> {
              from_index: Integer,
              to_index: Integer,
              types: ::Array[String]
            }
          end
        end

        type place =
          {
            id: String,
            bounding_box: ::Hash[Symbol, top],
            country: String,
            country_code: String,
            full_name: String,
            name: String,
            place_type: String,
            url: String
          }

        class Place < XTwitterScraper::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader bounding_box: ::Hash[Symbol, top]?

          def bounding_box=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader country: String?

          def country=: (String) -> String

          attr_reader country_code: String?

          def country_code=: (String) -> String

          attr_reader full_name: String?

          def full_name=: (String) -> String

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader place_type: String?

          def place_type=: (String) -> String

          attr_reader url: String?

          def url=: (String) -> String

          def initialize: (
            ?id: String,
            ?bounding_box: ::Hash[Symbol, top],
            ?country: String,
            ?country_code: String,
            ?full_name: String,
            ?name: String,
            ?place_type: String,
            ?url: String
          ) -> void

          def to_hash: -> {
            id: String,
            bounding_box: ::Hash[Symbol, top],
            country: String,
            country_code: String,
            full_name: String,
            name: String,
            place_type: String,
            url: String
          }
        end

        type previous_counts =
          {
            bookmark_count: Integer,
            like_count: Integer,
            quote_count: Integer,
            reply_count: Integer,
            retweet_count: Integer
          }

        class PreviousCounts < XTwitterScraper::Internal::Type::BaseModel
          attr_reader bookmark_count: Integer?

          def bookmark_count=: (Integer) -> Integer

          attr_reader like_count: Integer?

          def like_count=: (Integer) -> Integer

          attr_reader quote_count: Integer?

          def quote_count=: (Integer) -> Integer

          attr_reader reply_count: Integer?

          def reply_count=: (Integer) -> Integer

          attr_reader retweet_count: Integer?

          def retweet_count=: (Integer) -> Integer

          def initialize: (
            ?bookmark_count: Integer,
            ?like_count: Integer,
            ?quote_count: Integer,
            ?reply_count: Integer,
            ?retweet_count: Integer
          ) -> void

          def to_hash: -> {
            bookmark_count: Integer,
            like_count: Integer,
            quote_count: Integer,
            reply_count: Integer,
            retweet_count: Integer
          }
        end
      end
    end
  end
end
