# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    module X
      type tweet_search_params =
        {
          q: String,
          advanced_query: String,
          any_words: String,
          bounding_box: String,
          cashtags: String,
          conversation_id: String,
          cursor: String,
          exact_phrase: String,
          exclude_words: String,
          from_user: String,
          hashtags: String,
          in_reply_to_tweet_id: String,
          language: String,
          limit: Integer,
          list_id: String,
          media_type: XTwitterScraper::Models::X::TweetSearchParams::media_type,
          mentioning: String,
          min_faves: Integer,
          min_quotes: Integer,
          min_replies: Integer,
          min_retweets: Integer,
          place: String,
          place_country: String,
          point_radius: String,
          query_type: XTwitterScraper::Models::X::TweetSearchParams::query_type,
          quotes: XTwitterScraper::Models::X::TweetSearchParams::quotes,
          quotes_of_tweet_id: String,
          replies: XTwitterScraper::Models::X::TweetSearchParams::replies,
          retweets: XTwitterScraper::Models::X::TweetSearchParams::retweets,
          retweets_of_tweet_id: String,
          since_date: Date,
          since_time: String,
          to_user: String,
          until_date: Date,
          until_time: String,
          url: String,
          verified_only: bool
        }
        & XTwitterScraper::Internal::Type::request_parameters

      class TweetSearchParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor q: String

        attr_reader advanced_query: String?

        def advanced_query=: (String) -> String

        attr_reader any_words: String?

        def any_words=: (String) -> String

        attr_reader bounding_box: String?

        def bounding_box=: (String) -> String

        attr_reader cashtags: String?

        def cashtags=: (String) -> String

        attr_reader conversation_id: String?

        def conversation_id=: (String) -> String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader exact_phrase: String?

        def exact_phrase=: (String) -> String

        attr_reader exclude_words: String?

        def exclude_words=: (String) -> String

        attr_reader from_user: String?

        def from_user=: (String) -> String

        attr_reader hashtags: String?

        def hashtags=: (String) -> String

        attr_reader in_reply_to_tweet_id: String?

        def in_reply_to_tweet_id=: (String) -> String

        attr_reader language: String?

        def language=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader list_id: String?

        def list_id=: (String) -> String

        attr_reader media_type: XTwitterScraper::Models::X::TweetSearchParams::media_type?

        def media_type=: (
          XTwitterScraper::Models::X::TweetSearchParams::media_type
        ) -> XTwitterScraper::Models::X::TweetSearchParams::media_type

        attr_reader mentioning: String?

        def mentioning=: (String) -> String

        attr_reader min_faves: Integer?

        def min_faves=: (Integer) -> Integer

        attr_reader min_quotes: Integer?

        def min_quotes=: (Integer) -> Integer

        attr_reader min_replies: Integer?

        def min_replies=: (Integer) -> Integer

        attr_reader min_retweets: Integer?

        def min_retweets=: (Integer) -> Integer

        attr_reader place: String?

        def place=: (String) -> String

        attr_reader place_country: String?

        def place_country=: (String) -> String

        attr_reader point_radius: String?

        def point_radius=: (String) -> String

        attr_reader query_type: XTwitterScraper::Models::X::TweetSearchParams::query_type?

        def query_type=: (
          XTwitterScraper::Models::X::TweetSearchParams::query_type
        ) -> XTwitterScraper::Models::X::TweetSearchParams::query_type

        attr_reader quotes: XTwitterScraper::Models::X::TweetSearchParams::quotes?

        def quotes=: (
          XTwitterScraper::Models::X::TweetSearchParams::quotes
        ) -> XTwitterScraper::Models::X::TweetSearchParams::quotes

        attr_reader quotes_of_tweet_id: String?

        def quotes_of_tweet_id=: (String) -> String

        attr_reader replies: XTwitterScraper::Models::X::TweetSearchParams::replies?

        def replies=: (
          XTwitterScraper::Models::X::TweetSearchParams::replies
        ) -> XTwitterScraper::Models::X::TweetSearchParams::replies

        attr_reader retweets: XTwitterScraper::Models::X::TweetSearchParams::retweets?

        def retweets=: (
          XTwitterScraper::Models::X::TweetSearchParams::retweets
        ) -> XTwitterScraper::Models::X::TweetSearchParams::retweets

        attr_reader retweets_of_tweet_id: String?

        def retweets_of_tweet_id=: (String) -> String

        attr_reader since_date: Date?

        def since_date=: (Date) -> Date

        attr_reader since_time: String?

        def since_time=: (String) -> String

        attr_reader to_user: String?

        def to_user=: (String) -> String

        attr_reader until_date: Date?

        def until_date=: (Date) -> Date

        attr_reader until_time: String?

        def until_time=: (String) -> String

        attr_reader url: String?

        def url=: (String) -> String

        attr_reader verified_only: bool?

        def verified_only=: (bool) -> bool

        def initialize: (
          q: String,
          ?advanced_query: String,
          ?any_words: String,
          ?bounding_box: String,
          ?cashtags: String,
          ?conversation_id: String,
          ?cursor: String,
          ?exact_phrase: String,
          ?exclude_words: String,
          ?from_user: String,
          ?hashtags: String,
          ?in_reply_to_tweet_id: String,
          ?language: String,
          ?limit: Integer,
          ?list_id: String,
          ?media_type: XTwitterScraper::Models::X::TweetSearchParams::media_type,
          ?mentioning: String,
          ?min_faves: Integer,
          ?min_quotes: Integer,
          ?min_replies: Integer,
          ?min_retweets: Integer,
          ?place: String,
          ?place_country: String,
          ?point_radius: String,
          ?query_type: XTwitterScraper::Models::X::TweetSearchParams::query_type,
          ?quotes: XTwitterScraper::Models::X::TweetSearchParams::quotes,
          ?quotes_of_tweet_id: String,
          ?replies: XTwitterScraper::Models::X::TweetSearchParams::replies,
          ?retweets: XTwitterScraper::Models::X::TweetSearchParams::retweets,
          ?retweets_of_tweet_id: String,
          ?since_date: Date,
          ?since_time: String,
          ?to_user: String,
          ?until_date: Date,
          ?until_time: String,
          ?url: String,
          ?verified_only: bool,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          q: String,
          advanced_query: String,
          any_words: String,
          bounding_box: String,
          cashtags: String,
          conversation_id: String,
          cursor: String,
          exact_phrase: String,
          exclude_words: String,
          from_user: String,
          hashtags: String,
          in_reply_to_tweet_id: String,
          language: String,
          limit: Integer,
          list_id: String,
          media_type: XTwitterScraper::Models::X::TweetSearchParams::media_type,
          mentioning: String,
          min_faves: Integer,
          min_quotes: Integer,
          min_replies: Integer,
          min_retweets: Integer,
          place: String,
          place_country: String,
          point_radius: String,
          query_type: XTwitterScraper::Models::X::TweetSearchParams::query_type,
          quotes: XTwitterScraper::Models::X::TweetSearchParams::quotes,
          quotes_of_tweet_id: String,
          replies: XTwitterScraper::Models::X::TweetSearchParams::replies,
          retweets: XTwitterScraper::Models::X::TweetSearchParams::retweets,
          retweets_of_tweet_id: String,
          since_date: Date,
          since_time: String,
          to_user: String,
          until_date: Date,
          until_time: String,
          url: String,
          verified_only: bool,
          request_options: XTwitterScraper::RequestOptions
        }

        type media_type = :images | :videos | :gifs | :media | :links | :none

        module MediaType
          extend XTwitterScraper::Internal::Type::Enum

          IMAGES: :images
          VIDEOS: :videos
          GIFS: :gifs
          MEDIA: :media
          LINKS: :links
          NONE: :none

          def self?.values: -> ::Array[XTwitterScraper::Models::X::TweetSearchParams::media_type]
        end

        type query_type = :Latest | :Top

        module QueryType
          extend XTwitterScraper::Internal::Type::Enum

          LATEST: :Latest
          TOP: :Top

          def self?.values: -> ::Array[XTwitterScraper::Models::X::TweetSearchParams::query_type]
        end

        type quotes = :include | :exclude | :only

        module Quotes
          extend XTwitterScraper::Internal::Type::Enum

          INCLUDE: :include
          EXCLUDE: :exclude
          ONLY: :only

          def self?.values: -> ::Array[XTwitterScraper::Models::X::TweetSearchParams::quotes]
        end

        type replies = :include | :exclude | :only

        module Replies
          extend XTwitterScraper::Internal::Type::Enum

          INCLUDE: :include
          EXCLUDE: :exclude
          ONLY: :only

          def self?.values: -> ::Array[XTwitterScraper::Models::X::TweetSearchParams::replies]
        end

        type retweets = :include | :exclude | :only

        module Retweets
          extend XTwitterScraper::Internal::Type::Enum

          INCLUDE: :include
          EXCLUDE: :exclude
          ONLY: :only

          def self?.values: -> ::Array[XTwitterScraper::Models::X::TweetSearchParams::retweets]
        end
      end
    end
  end
end
