module XTwitterScraper
  module Models
    module X
      type tweet_author = { followers: Integer, verified: bool }

      class TweetAuthor < XTwitterScraper::Models::UserProfile
        def followers: -> Integer

        def followers=: (Integer _) -> Integer

        def verified: -> bool

        def verified=: (bool _) -> bool

        def initialize: (followers: Integer, verified: bool) -> void

        def to_hash: -> { followers: Integer, verified: bool }
      end
    end
  end
end
