module XTwitterScraper
  module Models
    module X
      type tweet_author = {  }

      class TweetAuthor < XTwitterScraper::Models::UserProfile
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
