module XTwitterScraper
  module Models
    module X
      type user_retrieve_followers_response =
        {
          has_next_page: bool,
          next_cursor: String,
          users: ::Array[XTwitterScraper::Models::X::UserRetrieveFollowersResponse::User]
        }

      class UserRetrieveFollowersResponse < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor has_next_page: bool

        attr_accessor next_cursor: String

        attr_accessor users: ::Array[XTwitterScraper::Models::X::UserRetrieveFollowersResponse::User]

        def initialize: (
          has_next_page: bool,
          next_cursor: String,
          users: ::Array[XTwitterScraper::Models::X::UserRetrieveFollowersResponse::User]
        ) -> void

        def to_hash: -> {
          has_next_page: bool,
          next_cursor: String,
          users: ::Array[XTwitterScraper::Models::X::UserRetrieveFollowersResponse::User]
        }

        type user =
          {
            id: String,
            name: String,
            username: String,
            created_at: String,
            description: String,
            followers: Integer,
            following: Integer,
            location: String,
            profile_picture: String,
            statuses_count: Integer,
            verified: bool
          }

        class User < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String

          attr_accessor username: String

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader followers: Integer?

          def followers=: (Integer) -> Integer

          attr_reader following: Integer?

          def following=: (Integer) -> Integer

          attr_reader location: String?

          def location=: (String) -> String

          attr_reader profile_picture: String?

          def profile_picture=: (String) -> String

          attr_reader statuses_count: Integer?

          def statuses_count=: (Integer) -> Integer

          attr_reader verified: bool?

          def verified=: (bool) -> bool

          def initialize: (
            id: String,
            name: String,
            username: String,
            ?created_at: String,
            ?description: String,
            ?followers: Integer,
            ?following: Integer,
            ?location: String,
            ?profile_picture: String,
            ?statuses_count: Integer,
            ?verified: bool
          ) -> void

          def to_hash: -> {
            id: String,
            name: String,
            username: String,
            created_at: String,
            description: String,
            followers: Integer,
            following: Integer,
            location: String,
            profile_picture: String,
            statuses_count: Integer,
            verified: bool
          }
        end
      end
    end
  end
end
