module XTwitterScraper
  module Models
    module X
      type user_retrieve_batch_params =
        { ids: String } & XTwitterScraper::Internal::Type::request_parameters

      class UserRetrieveBatchParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor ids: String

        def initialize: (
          ids: String,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          ids: String,
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
