module XTwitterScraper
  module Models
    module X
      type user_retrieve_following_params =
        {
          id: String,
          after: String,
          cursor: String,
          limit: Integer,
          page_size: Integer
        }
        & XTwitterScraper::Internal::Type::request_parameters

      class UserRetrieveFollowingParams < XTwitterScraper::Internal::Type::BaseModel
        extend XTwitterScraper::Internal::Type::RequestParameters::Converter
        include XTwitterScraper::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page_size: Integer?

        def page_size=: (Integer) -> Integer

        def initialize: (
          id: String,
          ?after: String,
          ?cursor: String,
          ?limit: Integer,
          ?page_size: Integer,
          ?request_options: XTwitterScraper::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          after: String,
          cursor: String,
          limit: Integer,
          page_size: Integer,
          request_options: XTwitterScraper::RequestOptions
        }
      end
    end
  end
end
