module XTwitterScraper
  module Models
    class XAccount = X::XAccount

    module X
      type x_account =
        {
          id: String,
          created_at: Time,
          status: String,
          x_user_id: String,
          x_username: String
        }

      class XAccount < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor status: String

        attr_accessor x_user_id: String

        attr_accessor x_username: String

        def initialize: (
          id: String,
          created_at: Time,
          status: String,
          x_user_id: String,
          x_username: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          status: String,
          x_user_id: String,
          x_username: String
        }
      end
    end
  end
end
