# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class Compose
      def create: (
        body: XTwitterScraper::Models::ComposeCreateParams::body,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::compose_create_response

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
