module XTwitterScraper
  module Resources
    class Compose
      def create: (
        body: XTwitterScraper::Models::ComposeCreateParams::body,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::compose_create_response

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
