# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class Credits
      def redirect_topup_checkout: (
        session_id: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> nil

      def retrieve_balance: (
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::CreditRetrieveBalanceResponse

      def retrieve_topup_status: (
        session_id: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::CreditRetrieveTopupStatusResponse

      def topup_balance: (
        dollars: Integer,
        ?locale: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::CreditTopupBalanceResponse

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
