module XTwitterScraper
  module Resources
    class Drafts
      def create: (
        text: String,
        ?goal: XTwitterScraper::Models::DraftCreateParams::goal,
        ?topic: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::DraftDetail

      def retrieve: (
        String id,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::DraftDetail

      def list: (
        ?after_cursor: String,
        ?limit: Integer,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::DraftListResponse

      def delete: (
        String id,
        ?request_options: XTwitterScraper::request_opts
      ) -> nil

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
