# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class Extractions
      def retrieve: (
        String id,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::ExtractionRetrieveResponse

      def list: (
        ?cursor: String,
        ?limit: Integer,
        ?status: XTwitterScraper::Models::ExtractionListParams::status,
        ?tool_type: XTwitterScraper::Models::ExtractionListParams::tool_type,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::ExtractionListResponse

      def estimate_cost: (
        tool_type: XTwitterScraper::Models::ExtractionEstimateCostParams::tool_type,
        ?advanced_query: String,
        ?any_words: String,
        ?bounding_box: String,
        ?cashtags: String,
        ?conversation_id: String,
        ?exact_phrase: String,
        ?exclude_words: String,
        ?from_user: String,
        ?hashtags: String,
        ?in_reply_to_tweet_id: String,
        ?language: String,
        ?list_id: String,
        ?media_type: XTwitterScraper::Models::ExtractionEstimateCostParams::media_type,
        ?mentioning: String,
        ?min_faves: Integer,
        ?min_quotes: Integer,
        ?min_replies: Integer,
        ?min_retweets: Integer,
        ?place: String,
        ?place_country: String,
        ?point_radius: String,
        ?quotes: XTwitterScraper::Models::ExtractionEstimateCostParams::quotes,
        ?quotes_of_tweet_id: String,
        ?replies: XTwitterScraper::Models::ExtractionEstimateCostParams::replies,
        ?results_limit: Integer,
        ?retweets: XTwitterScraper::Models::ExtractionEstimateCostParams::retweets,
        ?retweets_of_tweet_id: String,
        ?search_query: String,
        ?since_date: Date,
        ?target_community_id: String,
        ?target_list_id: String,
        ?target_space_id: String,
        ?target_tweet_id: String,
        ?target_username: String,
        ?to_user: String,
        ?until_date: Date,
        ?url: String,
        ?verified_only: bool,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::ExtractionEstimateCostResponse

      def export_results: (
        String id,
        format_: XTwitterScraper::Models::ExtractionExportResultsParams::format_,
        ?request_options: XTwitterScraper::request_opts
      ) -> StringIO

      def run: (
        tool_type: XTwitterScraper::Models::ExtractionRunParams::tool_type,
        ?advanced_query: String,
        ?any_words: String,
        ?bounding_box: String,
        ?cashtags: String,
        ?conversation_id: String,
        ?exact_phrase: String,
        ?exclude_words: String,
        ?from_user: String,
        ?hashtags: String,
        ?in_reply_to_tweet_id: String,
        ?language: String,
        ?list_id: String,
        ?media_type: XTwitterScraper::Models::ExtractionRunParams::media_type,
        ?mentioning: String,
        ?min_faves: Integer,
        ?min_quotes: Integer,
        ?min_replies: Integer,
        ?min_retweets: Integer,
        ?place: String,
        ?place_country: String,
        ?point_radius: String,
        ?quotes: XTwitterScraper::Models::ExtractionRunParams::quotes,
        ?quotes_of_tweet_id: String,
        ?replies: XTwitterScraper::Models::ExtractionRunParams::replies,
        ?results_limit: Integer,
        ?retweets: XTwitterScraper::Models::ExtractionRunParams::retweets,
        ?retweets_of_tweet_id: String,
        ?search_query: String,
        ?since_date: Date,
        ?target_community_id: String,
        ?target_list_id: String,
        ?target_space_id: String,
        ?target_tweet_id: String,
        ?target_username: String,
        ?to_user: String,
        ?until_date: Date,
        ?url: String,
        ?verified_only: bool,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::ExtractionRunResponse

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
