module XTwitterScraper
  module Resources
    class Radar
      def retrieve_trending_topics: (
        ?category: String,
        ?count: Integer,
        ?hours: Integer,
        ?region: String,
        ?source: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::RadarRetrieveTrendingTopicsResponse

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
