module XTwitterScraper
  module Resources
    class Radar
      def retrieve_trending_topics: (
        ?after: String,
        ?category: XTwitterScraper::Models::RadarRetrieveTrendingTopicsParams::category,
        ?hours: Integer,
        ?limit: Integer,
        ?region: String,
        ?source: XTwitterScraper::Models::RadarRetrieveTrendingTopicsParams::source,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::RadarRetrieveTrendingTopicsResponse

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
