module XTwitterScraper
  module Resources
    class Styles
      def list: (
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::StyleListResponse

      def analyze: (
        username: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::StyleAnalyzeResponse

      def compare: (
        username1: String,
        username2: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::StyleCompareResponse

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
