# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class Subscribe
      def create: (
        ?tier: XTwitterScraper::Models::SubscribeCreateParams::tier,
        ?request_options: XTwitterScraper::request_opts
      ) -> XTwitterScraper::Models::SubscribeCreateResponse

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
