# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Resources
    class Support
      attr_reader tickets: XTwitterScraper::Resources::Support::Tickets

      def initialize: (client: XTwitterScraper::Client) -> void
    end
  end
end
