module XTwitterScraper
  module Models
    module X
      module Communities
        type join_delete_all_response = { success: true }

        class JoinDeleteAllResponse < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor success: true

          def initialize: (?success: true) -> void

          def to_hash: -> { success: true }
        end
      end
    end
  end
end
