module XTwitterScraper
  module Models
    module X
      module Communities
        type join_create_response =
          { community_id: String, community_name: String, success: true }

        class JoinCreateResponse < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor community_id: String

          attr_accessor community_name: String

          attr_accessor success: true

          def initialize: (
            community_id: String,
            community_name: String,
            ?success: true
          ) -> void

          def to_hash: -> {
            community_id: String,
            community_name: String,
            success: true
          }
        end
      end
    end
  end
end
