module XTwitterScraper
  module Models
    module X
      module Communities
        type tweet_list_params =
          { q: String, cursor: String, query_type: String }
          & XTwitterScraper::Internal::Type::request_parameters

        class TweetListParams < XTwitterScraper::Internal::Type::BaseModel
          extend XTwitterScraper::Internal::Type::RequestParameters::Converter
          include XTwitterScraper::Internal::Type::RequestParameters

          attr_accessor q: String

          attr_reader cursor: String?

          def cursor=: (String) -> String

          attr_reader query_type: String?

          def query_type=: (String) -> String

          def initialize: (
            q: String,
            ?cursor: String,
            ?query_type: String,
            ?request_options: XTwitterScraper::request_opts
          ) -> void

          def to_hash: -> {
            q: String,
            cursor: String,
            query_type: String,
            request_options: XTwitterScraper::RequestOptions
          }
        end
      end
    end
  end
end
