module XTwitterScraper
  module Models
    type account_retrieve_response =
      {
        monitors_allowed: Integer,
        monitors_used: Integer,
        plan: XTwitterScraper::Models::AccountRetrieveResponse::plan,
        credit_info: XTwitterScraper::Models::AccountRetrieveResponse::CreditInfo
      }

    class AccountRetrieveResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor monitors_allowed: Integer

      attr_accessor monitors_used: Integer

      attr_accessor plan: XTwitterScraper::Models::AccountRetrieveResponse::plan

      attr_reader credit_info: XTwitterScraper::Models::AccountRetrieveResponse::CreditInfo?

      def credit_info=: (
        XTwitterScraper::Models::AccountRetrieveResponse::CreditInfo
      ) -> XTwitterScraper::Models::AccountRetrieveResponse::CreditInfo

      def initialize: (
        monitors_allowed: Integer,
        monitors_used: Integer,
        plan: XTwitterScraper::Models::AccountRetrieveResponse::plan,
        ?credit_info: XTwitterScraper::Models::AccountRetrieveResponse::CreditInfo
      ) -> void

      def to_hash: -> {
        monitors_allowed: Integer,
        monitors_used: Integer,
        plan: XTwitterScraper::Models::AccountRetrieveResponse::plan,
        credit_info: XTwitterScraper::Models::AccountRetrieveResponse::CreditInfo
      }

      type plan = :active | :inactive

      module Plan
        extend XTwitterScraper::Internal::Type::Enum

        ACTIVE: :active
        INACTIVE: :inactive

        def self?.values: -> ::Array[XTwitterScraper::Models::AccountRetrieveResponse::plan]
      end

      type credit_info =
        {
          auto_topup_enabled: bool,
          balance: Integer,
          lifetime_purchased: Integer,
          lifetime_used: Integer
        }

      class CreditInfo < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor auto_topup_enabled: bool

        attr_accessor balance: Integer

        attr_accessor lifetime_purchased: Integer

        attr_accessor lifetime_used: Integer

        def initialize: (
          auto_topup_enabled: bool,
          balance: Integer,
          lifetime_purchased: Integer,
          lifetime_used: Integer
        ) -> void

        def to_hash: -> {
          auto_topup_enabled: bool,
          balance: Integer,
          lifetime_purchased: Integer,
          lifetime_used: Integer
        }
      end
    end
  end
end
