module XTwitterScraper
  module Models
    type account_update_locale_response = { success: true }

    class AccountUpdateLocaleResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor success: true

      def initialize: (?success: true) -> void

      def to_hash: -> { success: true }
    end
  end
end
