# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type account_set_x_username_params =
      { username: String } & XTwitterScraper::Internal::Type::request_parameters

    class AccountSetXUsernameParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor username: String

      def initialize: (
        username: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        username: String,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
