module XTwitterScraper
  module Models
    type api_key_create_response =
      {
        id: String,
        created_at: Time,
        full_key: String,
        name: String,
        prefix: String
      }

    class APIKeyCreateResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor full_key: String

      attr_accessor name: String

      attr_accessor prefix: String

      def initialize: (
        id: String,
        created_at: Time,
        full_key: String,
        name: String,
        prefix: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        full_key: String,
        name: String,
        prefix: String
      }
    end
  end
end
