module XTwitterScraper
  module Models
    type api_key_revoke_response = { success: true }

    class APIKeyRevokeResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor success: true

      def initialize: (?success: true) -> void

      def to_hash: -> { success: true }
    end
  end
end
