module XTwitterScraper
  module Models
    type api_key_list_response = { keys: ::Array[XTwitterScraper::APIKey] }

    class APIKeyListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor keys: ::Array[XTwitterScraper::APIKey]

      def initialize: (keys: ::Array[XTwitterScraper::APIKey]) -> void

      def to_hash: -> { keys: ::Array[XTwitterScraper::APIKey] }
    end
  end
end
