module XTwitterScraper
  module Models
    type bot_track_usage_params =
      {
        input_tokens: Integer,
        output_tokens: Integer,
        platform_user_id: String
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class BotTrackUsageParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor input_tokens: Integer

      attr_accessor output_tokens: Integer

      attr_accessor platform_user_id: String

      def initialize: (
        input_tokens: Integer,
        output_tokens: Integer,
        platform_user_id: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        input_tokens: Integer,
        output_tokens: Integer,
        platform_user_id: String,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
