module XTwitterScraper
  module Models
    type credit_topup_balance_response = { redirect_url: String, url: String }

    class CreditTopupBalanceResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor redirect_url: String

      attr_accessor url: String

      def initialize: (redirect_url: String, url: String) -> void

      def to_hash: -> { redirect_url: String, url: String }
    end
  end
end
