# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type credit_topup_balance_params =
      { dollars: Integer, locale: String }
      & XTwitterScraper::Internal::Type::request_parameters

    class CreditTopupBalanceParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor dollars: Integer

      attr_reader locale: String?

      def locale=: (String) -> String

      def initialize: (
        dollars: Integer,
        ?locale: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        dollars: Integer,
        locale: String,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
