# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type draft_list_response =
      {
        drafts: ::Array[XTwitterScraper::Draft],
        has_more: bool,
        next_cursor: String
      }

    class DraftListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor drafts: ::Array[XTwitterScraper::Draft]

      attr_accessor has_more: bool

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        drafts: ::Array[XTwitterScraper::Draft],
        has_more: bool,
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        drafts: ::Array[XTwitterScraper::Draft],
        has_more: bool,
        next_cursor: String
      }
    end
  end
end
