# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type draft =
      {
        id: String,
        created_at: Time,
        text: String,
        goal: String,
        topic: String
      }

    class Draft < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor text: String

      attr_reader goal: String?

      def goal=: (String) -> String

      attr_reader topic: String?

      def topic=: (String) -> String

      def initialize: (
        id: String,
        created_at: Time,
        text: String,
        ?goal: String,
        ?topic: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        text: String,
        goal: String,
        topic: String
      }
    end
  end
end
