module XTwitterScraper
  module Models
    type draw_list_response =
      {
        draws: ::Array[XTwitterScraper::DrawListItem],
        has_more: bool,
        next_cursor: String
      }

    class DrawListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor draws: ::Array[XTwitterScraper::DrawListItem]

      attr_accessor has_more: bool

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        draws: ::Array[XTwitterScraper::DrawListItem],
        has_more: bool,
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        draws: ::Array[XTwitterScraper::DrawListItem],
        has_more: bool,
        next_cursor: String
      }
    end
  end
end
