module XTwitterScraper
  module Models
    type draw_retrieve_response =
      {
        draw: XTwitterScraper::DrawDetail,
        winners: ::Array[XTwitterScraper::Winner]
      }

    class DrawRetrieveResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor draw: XTwitterScraper::DrawDetail

      attr_accessor winners: ::Array[XTwitterScraper::Winner]

      def initialize: (
        draw: XTwitterScraper::DrawDetail,
        winners: ::Array[XTwitterScraper::Winner]
      ) -> void

      def to_hash: -> {
        draw: XTwitterScraper::DrawDetail,
        winners: ::Array[XTwitterScraper::Winner]
      }
    end
  end
end
