module XTwitterScraper
  module Models
    type draw_run_response =
      {
        id: String,
        total_entries: Integer,
        tweet_id: String,
        valid_entries: Integer,
        winners: ::Array[XTwitterScraper::Winner]
      }

    class DrawRunResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor total_entries: Integer

      attr_accessor tweet_id: String

      attr_accessor valid_entries: Integer

      attr_accessor winners: ::Array[XTwitterScraper::Winner]

      def initialize: (
        id: String,
        total_entries: Integer,
        tweet_id: String,
        valid_entries: Integer,
        winners: ::Array[XTwitterScraper::Winner]
      ) -> void

      def to_hash: -> {
        id: String,
        total_entries: Integer,
        tweet_id: String,
        valid_entries: Integer,
        winners: ::Array[XTwitterScraper::Winner]
      }
    end
  end
end
