module XTwitterScraper
  module Models
    type draw_list_response =
      {
        draws: ::Array[XTwitterScraper::Models::DrawListResponse::Draw],
        has_more: bool,
        next_cursor: String
      }

    class DrawListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor draws: ::Array[XTwitterScraper::Models::DrawListResponse::Draw]

      attr_accessor has_more: bool

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        draws: ::Array[XTwitterScraper::Models::DrawListResponse::Draw],
        has_more: bool,
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        draws: ::Array[XTwitterScraper::Models::DrawListResponse::Draw],
        has_more: bool,
        next_cursor: String
      }

      type draw =
        {
          id: String,
          created_at: Time,
          status: String,
          total_entries: Integer,
          tweet_url: String,
          valid_entries: Integer,
          drawn_at: Time
        }

      class Draw < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor status: String

        attr_accessor total_entries: Integer

        attr_accessor tweet_url: String

        attr_accessor valid_entries: Integer

        attr_reader drawn_at: Time?

        def drawn_at=: (Time) -> Time

        def initialize: (
          id: String,
          created_at: Time,
          status: String,
          total_entries: Integer,
          tweet_url: String,
          valid_entries: Integer,
          ?drawn_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          status: String,
          total_entries: Integer,
          tweet_url: String,
          valid_entries: Integer,
          drawn_at: Time
        }
      end
    end
  end
end
