module XTwitterScraper
  module Models
    type event_list_params =
      {
        after: String,
        event_type: XTwitterScraper::Models::EventListParams::event_type,
        limit: Integer,
        monitor_id: String
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class EventListParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader event_type: XTwitterScraper::Models::EventListParams::event_type?

      def event_type=: (
        XTwitterScraper::Models::EventListParams::event_type
      ) -> XTwitterScraper::Models::EventListParams::event_type

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader monitor_id: String?

      def monitor_id=: (String) -> String

      def initialize: (
        ?after: String,
        ?event_type: XTwitterScraper::Models::EventListParams::event_type,
        ?limit: Integer,
        ?monitor_id: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        event_type: XTwitterScraper::Models::EventListParams::event_type,
        limit: Integer,
        monitor_id: String,
        request_options: XTwitterScraper::RequestOptions
      }

      type event_type =
        :"tweet.new"
        | :"tweet.reply"
        | :"tweet.retweet"
        | :"tweet.quote"
        | :"follower.gained"
        | :"follower.lost"

      module EventType
        extend XTwitterScraper::Internal::Type::Enum

        TWEET_NEW: :"tweet.new"
        TWEET_REPLY: :"tweet.reply"
        TWEET_RETWEET: :"tweet.retweet"
        TWEET_QUOTE: :"tweet.quote"
        FOLLOWER_GAINED: :"follower.gained"
        FOLLOWER_LOST: :"follower.lost"

        def self?.values: -> ::Array[XTwitterScraper::Models::EventListParams::event_type]
      end
    end
  end
end
