module XTwitterScraper
  module Models
    type event_list_response =
      {
        events: ::Array[XTwitterScraper::Event],
        has_more: bool,
        next_cursor: String
      }

    class EventListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor events: ::Array[XTwitterScraper::Event]

      attr_accessor has_more: bool

      attr_reader next_cursor: String?

      def next_cursor=: (String) -> String

      def initialize: (
        events: ::Array[XTwitterScraper::Event],
        has_more: bool,
        ?next_cursor: String
      ) -> void

      def to_hash: -> {
        events: ::Array[XTwitterScraper::Event],
        has_more: bool,
        next_cursor: String
      }
    end
  end
end
