module XTwitterScraper
  module Models
    type event_type =
      :"tweet.new" | :"tweet.reply" | :"tweet.retweet" | :"tweet.quote"

    module EventType
      extend XTwitterScraper::Internal::Type::Enum

      TWEET_NEW: :"tweet.new"
      TWEET_REPLY: :"tweet.reply"
      TWEET_RETWEET: :"tweet.retweet"
      TWEET_QUOTE: :"tweet.quote"

      def self?.values: -> ::Array[XTwitterScraper::Models::event_type]
    end
  end
end
