# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type event =
      {
        id: String,
        data: ::Hash[Symbol, top],
        monitor_id: String,
        monitor_type: XTwitterScraper::Models::Event::monitor_type,
        occurred_at: Time,
        type: XTwitterScraper::Models::event_type,
        keyword_monitor_id: String,
        query: String,
        username: String
      }

    class Event < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor data: ::Hash[Symbol, top]

      attr_accessor monitor_id: String

      attr_accessor monitor_type: XTwitterScraper::Models::Event::monitor_type

      attr_accessor occurred_at: Time

      attr_accessor type: XTwitterScraper::Models::event_type

      attr_reader keyword_monitor_id: String?

      def keyword_monitor_id=: (String) -> String

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader username: String?

      def username=: (String) -> String

      def initialize: (
        id: String,
        data: ::Hash[Symbol, top],
        monitor_id: String,
        monitor_type: XTwitterScraper::Models::Event::monitor_type,
        occurred_at: Time,
        type: XTwitterScraper::Models::event_type,
        ?keyword_monitor_id: String,
        ?query: String,
        ?username: String
      ) -> void

      def to_hash: -> {
        id: String,
        data: ::Hash[Symbol, top],
        monitor_id: String,
        monitor_type: XTwitterScraper::Models::Event::monitor_type,
        occurred_at: Time,
        type: XTwitterScraper::Models::event_type,
        keyword_monitor_id: String,
        query: String,
        username: String
      }

      type monitor_type = :account | :keyword

      module MonitorType
        extend XTwitterScraper::Internal::Type::Enum

        ACCOUNT: :account
        KEYWORD: :keyword

        def self?.values: -> ::Array[XTwitterScraper::Models::Event::monitor_type]
      end
    end
  end
end
