module XTwitterScraper
  module Models
    type event_retrieve_response =
      {
        id: String,
        data: ::Hash[Symbol, top],
        monitor_id: String,
        occurred_at: Time,
        type: XTwitterScraper::Models::EventRetrieveResponse::type_,
        username: String,
        x_event_id: String
      }

    class EventRetrieveResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor data: ::Hash[Symbol, top]

      attr_accessor monitor_id: String

      attr_accessor occurred_at: Time

      attr_accessor type: XTwitterScraper::Models::EventRetrieveResponse::type_

      attr_accessor username: String

      attr_reader x_event_id: String?

      def x_event_id=: (String) -> String

      def initialize: (
        id: String,
        data: ::Hash[Symbol, top],
        monitor_id: String,
        occurred_at: Time,
        type: XTwitterScraper::Models::EventRetrieveResponse::type_,
        username: String,
        ?x_event_id: String
      ) -> void

      def to_hash: -> {
        id: String,
        data: ::Hash[Symbol, top],
        monitor_id: String,
        occurred_at: Time,
        type: XTwitterScraper::Models::EventRetrieveResponse::type_,
        username: String,
        x_event_id: String
      }

      type type_ =
        :"tweet.new"
        | :"tweet.reply"
        | :"tweet.retweet"
        | :"tweet.quote"
        | :"follower.gained"
        | :"follower.lost"

      module Type
        extend XTwitterScraper::Internal::Type::Enum

        TWEET_NEW: :"tweet.new"
        TWEET_REPLY: :"tweet.reply"
        TWEET_RETWEET: :"tweet.retweet"
        TWEET_QUOTE: :"tweet.quote"
        FOLLOWER_GAINED: :"follower.gained"
        FOLLOWER_LOST: :"follower.lost"

        def self?.values: -> ::Array[XTwitterScraper::Models::EventRetrieveResponse::type_]
      end
    end
  end
end
