module XTwitterScraper
  module Models
    type event_list_params =
      {
        after: String,
        event_type: XTwitterScraper::Models::event_type,
        limit: Integer,
        monitor_id: String
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class EventListParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader event_type: XTwitterScraper::Models::event_type?

      def event_type=: (
        XTwitterScraper::Models::event_type
      ) -> XTwitterScraper::Models::event_type

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader monitor_id: String?

      def monitor_id=: (String) -> String

      def initialize: (
        ?after: String,
        ?event_type: XTwitterScraper::Models::event_type,
        ?limit: Integer,
        ?monitor_id: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        event_type: XTwitterScraper::Models::event_type,
        limit: Integer,
        monitor_id: String,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
