# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type extraction_estimate_cost_params =
      {
        tool_type: XTwitterScraper::Models::ExtractionEstimateCostParams::tool_type,
        advanced_query: String,
        any_words: String,
        bio_contains: String,
        blue_verified_only: bool,
        bounding_box: String,
        card_name: String,
        cashtags: String,
        collection_strategy: XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy,
        conversation_id: String,
        dedupe_across_targets: bool,
        dedupe_mode: XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode,
        exact_phrase: String,
        exclude_original_author: bool,
        exclude_source: String,
        exclude_words: String,
        from_user: String,
        geocode: String,
        hashtags: String,
        has_location: bool,
        has_media_only: bool,
        has_website: bool,
        include_original_post: bool,
        include_search_terms: bool,
        include_target_metadata: bool,
        in_reply_to_tweet_id: String,
        language: String,
        list_id: String,
        location_contains: String,
        max_depth: Integer,
        max_followers: Integer,
        max_following: Integer,
        max_id: String,
        max_items_per_target: Integer,
        max_likes: Integer,
        max_pages_per_target: Integer,
        max_posts: Integer,
        max_quotes: Integer,
        max_replies: Integer,
        max_retweets: Integer,
        media_type: XTwitterScraper::Models::ExtractionEstimateCostParams::media_type,
        mentioning: String,
        min_account_age_days: Integer,
        min_bookmarks: Integer,
        min_faves: Integer,
        min_followers: Integer,
        min_following: Integer,
        min_posts: Integer,
        min_quotes: Integer,
        min_replies: Integer,
        min_retweets: Integer,
        min_views: Integer,
        native_retweets: bool,
        near: String,
        news: bool,
        overlap_mode: bool,
        place: String,
        place_country: String,
        point_radius: String,
        query_type: XTwitterScraper::Models::ExtractionEstimateCostParams::query_type,
        quotes: XTwitterScraper::Models::ExtractionEstimateCostParams::quotes,
        quotes_of_tweet_id: String,
        relation_targets: ::Array[XTwitterScraper::ExtractionEstimateCostParams::RelationTarget],
        replies: XTwitterScraper::Models::ExtractionEstimateCostParams::replies,
        results_limit: Integer,
        retweets: XTwitterScraper::Models::ExtractionEstimateCostParams::retweets,
        retweets_of_tweet_id: String,
        safe: bool,
        scope: XTwitterScraper::Models::ExtractionEstimateCostParams::scope,
        search_queries: ::Array[String],
        search_query: String,
        since_date: Date,
        since_id: String,
        since_time: XTwitterScraper::Models::ExtractionEstimateCostParams::since_time,
        sort: XTwitterScraper::Models::ExtractionEstimateCostParams::sort,
        source: String,
        start_cursor: String,
        target_community_id: String,
        target_community_ids: ::Array[String],
        target_list_id: String,
        target_list_ids: ::Array[String],
        targets: ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target],
        target_space_id: String,
        target_tweet_id: String,
        target_tweet_ids: ::Array[String],
        target_username: String,
        target_usernames: ::Array[String],
        to_user: String,
        until_date: Date,
        until_time: XTwitterScraper::Models::ExtractionEstimateCostParams::until_time,
        url: String,
        username_contains: String,
        verified_only: bool,
        verified_type: String,
        within: String,
        within_time: String
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class ExtractionEstimateCostParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor tool_type: XTwitterScraper::Models::ExtractionEstimateCostParams::tool_type

      attr_reader advanced_query: String?

      def advanced_query=: (String) -> String

      attr_reader any_words: String?

      def any_words=: (String) -> String

      attr_reader bio_contains: String?

      def bio_contains=: (String) -> String

      attr_reader blue_verified_only: bool?

      def blue_verified_only=: (bool) -> bool

      attr_reader bounding_box: String?

      def bounding_box=: (String) -> String

      attr_reader card_name: String?

      def card_name=: (String) -> String

      attr_reader cashtags: String?

      def cashtags=: (String) -> String

      attr_reader collection_strategy: XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy?

      def collection_strategy=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy

      attr_reader conversation_id: String?

      def conversation_id=: (String) -> String

      attr_reader dedupe_across_targets: bool?

      def dedupe_across_targets=: (bool) -> bool

      attr_reader dedupe_mode: XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode?

      def dedupe_mode=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode

      attr_reader exact_phrase: String?

      def exact_phrase=: (String) -> String

      attr_reader exclude_original_author: bool?

      def exclude_original_author=: (bool) -> bool

      attr_reader exclude_source: String?

      def exclude_source=: (String) -> String

      attr_reader exclude_words: String?

      def exclude_words=: (String) -> String

      attr_reader from_user: String?

      def from_user=: (String) -> String

      attr_reader geocode: String?

      def geocode=: (String) -> String

      attr_reader hashtags: String?

      def hashtags=: (String) -> String

      attr_reader has_location: bool?

      def has_location=: (bool) -> bool

      attr_reader has_media_only: bool?

      def has_media_only=: (bool) -> bool

      attr_reader has_website: bool?

      def has_website=: (bool) -> bool

      attr_reader include_original_post: bool?

      def include_original_post=: (bool) -> bool

      attr_reader include_search_terms: bool?

      def include_search_terms=: (bool) -> bool

      attr_reader include_target_metadata: bool?

      def include_target_metadata=: (bool) -> bool

      attr_reader in_reply_to_tweet_id: String?

      def in_reply_to_tweet_id=: (String) -> String

      attr_reader language: String?

      def language=: (String) -> String

      attr_reader list_id: String?

      def list_id=: (String) -> String

      attr_reader location_contains: String?

      def location_contains=: (String) -> String

      attr_reader max_depth: Integer?

      def max_depth=: (Integer) -> Integer

      attr_reader max_followers: Integer?

      def max_followers=: (Integer) -> Integer

      attr_reader max_following: Integer?

      def max_following=: (Integer) -> Integer

      attr_reader max_id: String?

      def max_id=: (String) -> String

      attr_reader max_items_per_target: Integer?

      def max_items_per_target=: (Integer) -> Integer

      attr_reader max_likes: Integer?

      def max_likes=: (Integer) -> Integer

      attr_reader max_pages_per_target: Integer?

      def max_pages_per_target=: (Integer) -> Integer

      attr_reader max_posts: Integer?

      def max_posts=: (Integer) -> Integer

      attr_reader max_quotes: Integer?

      def max_quotes=: (Integer) -> Integer

      attr_reader max_replies: Integer?

      def max_replies=: (Integer) -> Integer

      attr_reader max_retweets: Integer?

      def max_retweets=: (Integer) -> Integer

      attr_reader media_type: XTwitterScraper::Models::ExtractionEstimateCostParams::media_type?

      def media_type=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::media_type
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::media_type

      attr_reader mentioning: String?

      def mentioning=: (String) -> String

      attr_reader min_account_age_days: Integer?

      def min_account_age_days=: (Integer) -> Integer

      attr_reader min_bookmarks: Integer?

      def min_bookmarks=: (Integer) -> Integer

      attr_reader min_faves: Integer?

      def min_faves=: (Integer) -> Integer

      attr_reader min_followers: Integer?

      def min_followers=: (Integer) -> Integer

      attr_reader min_following: Integer?

      def min_following=: (Integer) -> Integer

      attr_reader min_posts: Integer?

      def min_posts=: (Integer) -> Integer

      attr_reader min_quotes: Integer?

      def min_quotes=: (Integer) -> Integer

      attr_reader min_replies: Integer?

      def min_replies=: (Integer) -> Integer

      attr_reader min_retweets: Integer?

      def min_retweets=: (Integer) -> Integer

      attr_reader min_views: Integer?

      def min_views=: (Integer) -> Integer

      attr_reader native_retweets: bool?

      def native_retweets=: (bool) -> bool

      attr_reader near: String?

      def near=: (String) -> String

      attr_reader news: bool?

      def news=: (bool) -> bool

      attr_reader overlap_mode: bool?

      def overlap_mode=: (bool) -> bool

      attr_reader place: String?

      def place=: (String) -> String

      attr_reader place_country: String?

      def place_country=: (String) -> String

      attr_reader point_radius: String?

      def point_radius=: (String) -> String

      attr_reader query_type: XTwitterScraper::Models::ExtractionEstimateCostParams::query_type?

      def query_type=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::query_type
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::query_type

      attr_reader quotes: XTwitterScraper::Models::ExtractionEstimateCostParams::quotes?

      def quotes=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::quotes
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::quotes

      attr_reader quotes_of_tweet_id: String?

      def quotes_of_tweet_id=: (String) -> String

      attr_reader relation_targets: ::Array[XTwitterScraper::ExtractionEstimateCostParams::RelationTarget]?

      def relation_targets=: (
        ::Array[XTwitterScraper::ExtractionEstimateCostParams::RelationTarget]
      ) -> ::Array[XTwitterScraper::ExtractionEstimateCostParams::RelationTarget]

      attr_reader replies: XTwitterScraper::Models::ExtractionEstimateCostParams::replies?

      def replies=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::replies
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::replies

      attr_reader results_limit: Integer?

      def results_limit=: (Integer) -> Integer

      attr_reader retweets: XTwitterScraper::Models::ExtractionEstimateCostParams::retweets?

      def retweets=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::retweets
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::retweets

      attr_reader retweets_of_tweet_id: String?

      def retweets_of_tweet_id=: (String) -> String

      attr_reader safe: bool?

      def safe=: (bool) -> bool

      attr_reader scope: XTwitterScraper::Models::ExtractionEstimateCostParams::scope?

      def scope=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::scope
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::scope

      attr_reader search_queries: ::Array[String]?

      def search_queries=: (::Array[String]) -> ::Array[String]

      attr_reader search_query: String?

      def search_query=: (String) -> String

      attr_reader since_date: Date?

      def since_date=: (Date) -> Date

      attr_reader since_id: String?

      def since_id=: (String) -> String

      attr_reader since_time: XTwitterScraper::Models::ExtractionEstimateCostParams::since_time?

      def since_time=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::since_time
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::since_time

      attr_reader sort: XTwitterScraper::Models::ExtractionEstimateCostParams::sort?

      def sort=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::sort
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::sort

      attr_reader source: String?

      def source=: (String) -> String

      attr_reader start_cursor: String?

      def start_cursor=: (String) -> String

      attr_reader target_community_id: String?

      def target_community_id=: (String) -> String

      attr_reader target_community_ids: ::Array[String]?

      def target_community_ids=: (::Array[String]) -> ::Array[String]

      attr_reader target_list_id: String?

      def target_list_id=: (String) -> String

      attr_reader target_list_ids: ::Array[String]?

      def target_list_ids=: (::Array[String]) -> ::Array[String]

      attr_reader targets: ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target]?

      def targets=: (
        ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target]
      ) -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target]

      attr_reader target_space_id: String?

      def target_space_id=: (String) -> String

      attr_reader target_tweet_id: String?

      def target_tweet_id=: (String) -> String

      attr_reader target_tweet_ids: ::Array[String]?

      def target_tweet_ids=: (::Array[String]) -> ::Array[String]

      attr_reader target_username: String?

      def target_username=: (String) -> String

      attr_reader target_usernames: ::Array[String]?

      def target_usernames=: (::Array[String]) -> ::Array[String]

      attr_reader to_user: String?

      def to_user=: (String) -> String

      attr_reader until_date: Date?

      def until_date=: (Date) -> Date

      attr_reader until_time: XTwitterScraper::Models::ExtractionEstimateCostParams::until_time?

      def until_time=: (
        XTwitterScraper::Models::ExtractionEstimateCostParams::until_time
      ) -> XTwitterScraper::Models::ExtractionEstimateCostParams::until_time

      attr_reader url: String?

      def url=: (String) -> String

      attr_reader username_contains: String?

      def username_contains=: (String) -> String

      attr_reader verified_only: bool?

      def verified_only=: (bool) -> bool

      attr_reader verified_type: String?

      def verified_type=: (String) -> String

      attr_reader within: String?

      def within=: (String) -> String

      attr_reader within_time: String?

      def within_time=: (String) -> String

      def initialize: (
        tool_type: XTwitterScraper::Models::ExtractionEstimateCostParams::tool_type,
        ?advanced_query: String,
        ?any_words: String,
        ?bio_contains: String,
        ?blue_verified_only: bool,
        ?bounding_box: String,
        ?card_name: String,
        ?cashtags: String,
        ?collection_strategy: XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy,
        ?conversation_id: String,
        ?dedupe_across_targets: bool,
        ?dedupe_mode: XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode,
        ?exact_phrase: String,
        ?exclude_original_author: bool,
        ?exclude_source: String,
        ?exclude_words: String,
        ?from_user: String,
        ?geocode: String,
        ?hashtags: String,
        ?has_location: bool,
        ?has_media_only: bool,
        ?has_website: bool,
        ?include_original_post: bool,
        ?include_search_terms: bool,
        ?include_target_metadata: bool,
        ?in_reply_to_tweet_id: String,
        ?language: String,
        ?list_id: String,
        ?location_contains: String,
        ?max_depth: Integer,
        ?max_followers: Integer,
        ?max_following: Integer,
        ?max_id: String,
        ?max_items_per_target: Integer,
        ?max_likes: Integer,
        ?max_pages_per_target: Integer,
        ?max_posts: Integer,
        ?max_quotes: Integer,
        ?max_replies: Integer,
        ?max_retweets: Integer,
        ?media_type: XTwitterScraper::Models::ExtractionEstimateCostParams::media_type,
        ?mentioning: String,
        ?min_account_age_days: Integer,
        ?min_bookmarks: Integer,
        ?min_faves: Integer,
        ?min_followers: Integer,
        ?min_following: Integer,
        ?min_posts: Integer,
        ?min_quotes: Integer,
        ?min_replies: Integer,
        ?min_retweets: Integer,
        ?min_views: Integer,
        ?native_retweets: bool,
        ?near: String,
        ?news: bool,
        ?overlap_mode: bool,
        ?place: String,
        ?place_country: String,
        ?point_radius: String,
        ?query_type: XTwitterScraper::Models::ExtractionEstimateCostParams::query_type,
        ?quotes: XTwitterScraper::Models::ExtractionEstimateCostParams::quotes,
        ?quotes_of_tweet_id: String,
        ?relation_targets: ::Array[XTwitterScraper::ExtractionEstimateCostParams::RelationTarget],
        ?replies: XTwitterScraper::Models::ExtractionEstimateCostParams::replies,
        ?results_limit: Integer,
        ?retweets: XTwitterScraper::Models::ExtractionEstimateCostParams::retweets,
        ?retweets_of_tweet_id: String,
        ?safe: bool,
        ?scope: XTwitterScraper::Models::ExtractionEstimateCostParams::scope,
        ?search_queries: ::Array[String],
        ?search_query: String,
        ?since_date: Date,
        ?since_id: String,
        ?since_time: XTwitterScraper::Models::ExtractionEstimateCostParams::since_time,
        ?sort: XTwitterScraper::Models::ExtractionEstimateCostParams::sort,
        ?source: String,
        ?start_cursor: String,
        ?target_community_id: String,
        ?target_community_ids: ::Array[String],
        ?target_list_id: String,
        ?target_list_ids: ::Array[String],
        ?targets: ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target],
        ?target_space_id: String,
        ?target_tweet_id: String,
        ?target_tweet_ids: ::Array[String],
        ?target_username: String,
        ?target_usernames: ::Array[String],
        ?to_user: String,
        ?until_date: Date,
        ?until_time: XTwitterScraper::Models::ExtractionEstimateCostParams::until_time,
        ?url: String,
        ?username_contains: String,
        ?verified_only: bool,
        ?verified_type: String,
        ?within: String,
        ?within_time: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        tool_type: XTwitterScraper::Models::ExtractionEstimateCostParams::tool_type,
        advanced_query: String,
        any_words: String,
        bio_contains: String,
        blue_verified_only: bool,
        bounding_box: String,
        card_name: String,
        cashtags: String,
        collection_strategy: XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy,
        conversation_id: String,
        dedupe_across_targets: bool,
        dedupe_mode: XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode,
        exact_phrase: String,
        exclude_original_author: bool,
        exclude_source: String,
        exclude_words: String,
        from_user: String,
        geocode: String,
        hashtags: String,
        has_location: bool,
        has_media_only: bool,
        has_website: bool,
        include_original_post: bool,
        include_search_terms: bool,
        include_target_metadata: bool,
        in_reply_to_tweet_id: String,
        language: String,
        list_id: String,
        location_contains: String,
        max_depth: Integer,
        max_followers: Integer,
        max_following: Integer,
        max_id: String,
        max_items_per_target: Integer,
        max_likes: Integer,
        max_pages_per_target: Integer,
        max_posts: Integer,
        max_quotes: Integer,
        max_replies: Integer,
        max_retweets: Integer,
        media_type: XTwitterScraper::Models::ExtractionEstimateCostParams::media_type,
        mentioning: String,
        min_account_age_days: Integer,
        min_bookmarks: Integer,
        min_faves: Integer,
        min_followers: Integer,
        min_following: Integer,
        min_posts: Integer,
        min_quotes: Integer,
        min_replies: Integer,
        min_retweets: Integer,
        min_views: Integer,
        native_retweets: bool,
        near: String,
        news: bool,
        overlap_mode: bool,
        place: String,
        place_country: String,
        point_radius: String,
        query_type: XTwitterScraper::Models::ExtractionEstimateCostParams::query_type,
        quotes: XTwitterScraper::Models::ExtractionEstimateCostParams::quotes,
        quotes_of_tweet_id: String,
        relation_targets: ::Array[XTwitterScraper::ExtractionEstimateCostParams::RelationTarget],
        replies: XTwitterScraper::Models::ExtractionEstimateCostParams::replies,
        results_limit: Integer,
        retweets: XTwitterScraper::Models::ExtractionEstimateCostParams::retweets,
        retweets_of_tweet_id: String,
        safe: bool,
        scope: XTwitterScraper::Models::ExtractionEstimateCostParams::scope,
        search_queries: ::Array[String],
        search_query: String,
        since_date: Date,
        since_id: String,
        since_time: XTwitterScraper::Models::ExtractionEstimateCostParams::since_time,
        sort: XTwitterScraper::Models::ExtractionEstimateCostParams::sort,
        source: String,
        start_cursor: String,
        target_community_id: String,
        target_community_ids: ::Array[String],
        target_list_id: String,
        target_list_ids: ::Array[String],
        targets: ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target],
        target_space_id: String,
        target_tweet_id: String,
        target_tweet_ids: ::Array[String],
        target_username: String,
        target_usernames: ::Array[String],
        to_user: String,
        until_date: Date,
        until_time: XTwitterScraper::Models::ExtractionEstimateCostParams::until_time,
        url: String,
        username_contains: String,
        verified_only: bool,
        verified_type: String,
        within: String,
        within_time: String,
        request_options: XTwitterScraper::RequestOptions
      }

      type tool_type =
        :article_extractor
        | :community_extractor
        | :community_moderator_explorer
        | :community_post_extractor
        | :community_search
        | :favoriters
        | :follower_explorer
        | :following_explorer
        | :list_follower_explorer
        | :list_member_extractor
        | :list_post_extractor
        | :mention_extractor
        | :people_search
        | :post_extractor
        | :quote_extractor
        | :reply_extractor
        | :repost_extractor
        | :space_explorer
        | :thread_extractor
        | :tweet_search_extractor
        | :user_likes
        | :user_media
        | :verified_follower_explorer

      module ToolType
        extend XTwitterScraper::Internal::Type::Enum

        ARTICLE_EXTRACTOR: :article_extractor
        COMMUNITY_EXTRACTOR: :community_extractor
        COMMUNITY_MODERATOR_EXPLORER: :community_moderator_explorer
        COMMUNITY_POST_EXTRACTOR: :community_post_extractor
        COMMUNITY_SEARCH: :community_search
        FAVORITERS: :favoriters
        FOLLOWER_EXPLORER: :follower_explorer
        FOLLOWING_EXPLORER: :following_explorer
        LIST_FOLLOWER_EXPLORER: :list_follower_explorer
        LIST_MEMBER_EXTRACTOR: :list_member_extractor
        LIST_POST_EXTRACTOR: :list_post_extractor
        MENTION_EXTRACTOR: :mention_extractor
        PEOPLE_SEARCH: :people_search
        POST_EXTRACTOR: :post_extractor
        QUOTE_EXTRACTOR: :quote_extractor
        REPLY_EXTRACTOR: :reply_extractor
        REPOST_EXTRACTOR: :repost_extractor
        SPACE_EXPLORER: :space_explorer
        THREAD_EXTRACTOR: :thread_extractor
        TWEET_SEARCH_EXTRACTOR: :tweet_search_extractor
        USER_LIKES: :user_likes
        USER_MEDIA: :user_media
        VERIFIED_FOLLOWER_EXPLORER: :verified_follower_explorer

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::tool_type]
      end

      type collection_strategy = :auto | :complete | :direct | :search | :thread

      module CollectionStrategy
        extend XTwitterScraper::Internal::Type::Enum

        AUTO: :auto
        COMPLETE: :complete
        DIRECT: :direct
        SEARCH: :search
        THREAD: :thread

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::collection_strategy]
      end

      type dedupe_mode = :none | :first | :merge

      module DedupeMode
        extend XTwitterScraper::Internal::Type::Enum

        NONE: :none
        FIRST: :first
        MERGE: :merge

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::dedupe_mode]
      end

      type media_type = :images | :videos | :gifs | :media | :links | :none

      module MediaType
        extend XTwitterScraper::Internal::Type::Enum

        IMAGES: :images
        VIDEOS: :videos
        GIFS: :gifs
        MEDIA: :media
        LINKS: :links
        NONE: :none

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::media_type]
      end

      type query_type = :Latest | :Top | :Both

      module QueryType
        extend XTwitterScraper::Internal::Type::Enum

        LATEST: :Latest
        TOP: :Top
        BOTH: :Both

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::query_type]
      end

      type quotes = :include | :exclude | :only

      module Quotes
        extend XTwitterScraper::Internal::Type::Enum

        INCLUDE: :include
        EXCLUDE: :exclude
        ONLY: :only

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::quotes]
      end

      type relation_target =
        {
          relation: XTwitterScraper::Models::ExtractionEstimateCostParams::RelationTarget::relation,
          value: String
        }

      class RelationTarget < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor relation: XTwitterScraper::Models::ExtractionEstimateCostParams::RelationTarget::relation

        attr_accessor value: String

        def initialize: (
          relation: XTwitterScraper::Models::ExtractionEstimateCostParams::RelationTarget::relation,
          value: String
        ) -> void

        def to_hash: -> {
          relation: XTwitterScraper::Models::ExtractionEstimateCostParams::RelationTarget::relation,
          value: String
        }

        type relation =
          :community_members
          | :followers
          | :following
          | :list_followers
          | :list_members
          | :verified_followers

        module Relation
          extend XTwitterScraper::Internal::Type::Enum

          COMMUNITY_MEMBERS: :community_members
          FOLLOWERS: :followers
          FOLLOWING: :following
          LIST_FOLLOWERS: :list_followers
          LIST_MEMBERS: :list_members
          VERIFIED_FOLLOWERS: :verified_followers

          def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::RelationTarget::relation]
        end
      end

      type replies = :include | :exclude | :only

      module Replies
        extend XTwitterScraper::Internal::Type::Enum

        INCLUDE: :include
        EXCLUDE: :exclude
        ONLY: :only

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::replies]
      end

      type retweets = :include | :exclude | :only

      module Retweets
        extend XTwitterScraper::Internal::Type::Enum

        INCLUDE: :include
        EXCLUDE: :exclude
        ONLY: :only

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::retweets]
      end

      type scope = :all | :direct | :nested

      module Scope
        extend XTwitterScraper::Internal::Type::Enum

        ALL: :all
        DIRECT: :direct
        NESTED: :nested

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::scope]
      end

      type since_time = Time | Integer

      module SinceTime
        extend XTwitterScraper::Internal::Type::Union

        def self?.variants: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::since_time]
      end

      type sort = :relevance | :latest | :oldest | :likes

      module Sort
        extend XTwitterScraper::Internal::Type::Enum

        RELEVANCE: :relevance
        LATEST: :latest
        OLDEST: :oldest
        LIKES: :likes

        def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::sort]
      end

      type target =
        String
        | XTwitterScraper::ExtractionEstimateCostParams::Target::UnionMember1

      module Target
        extend XTwitterScraper::Internal::Type::Union

        type union_member1 =
          {
            kind: XTwitterScraper::Models::ExtractionEstimateCostParams::Target::UnionMember1::kind,
            value: String
          }

        class UnionMember1 < XTwitterScraper::Internal::Type::BaseModel
          attr_accessor kind: XTwitterScraper::Models::ExtractionEstimateCostParams::Target::UnionMember1::kind

          attr_accessor value: String

          def initialize: (
            kind: XTwitterScraper::Models::ExtractionEstimateCostParams::Target::UnionMember1::kind,
            value: String
          ) -> void

          def to_hash: -> {
            kind: XTwitterScraper::Models::ExtractionEstimateCostParams::Target::UnionMember1::kind,
            value: String
          }

          type kind =
            :favoriters
            | :list
            | :profile
            | :profile_likes
            | :profile_media
            | :profile_replies
            | :quotes
            | :replies
            | :retweeters
            | :search
            | :thread
            | :tweet

          module Kind
            extend XTwitterScraper::Internal::Type::Enum

            FAVORITERS: :favoriters
            LIST: :list
            PROFILE: :profile
            PROFILE_LIKES: :profile_likes
            PROFILE_MEDIA: :profile_media
            PROFILE_REPLIES: :profile_replies
            QUOTES: :quotes
            REPLIES: :replies
            RETWEETERS: :retweeters
            SEARCH: :search
            THREAD: :thread
            TWEET: :tweet

            def self?.values: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::Target::UnionMember1::kind]
          end
        end

        def self?.variants: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::target]
      end

      type until_time = Time | Integer

      module UntilTime
        extend XTwitterScraper::Internal::Type::Union

        def self?.variants: -> ::Array[XTwitterScraper::Models::ExtractionEstimateCostParams::until_time]
      end
    end
  end
end
