module XTwitterScraper
  module Models
    type integration_send_test_response = { success: true }

    class IntegrationSendTestResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor success: true

      def initialize: (?success: true) -> void

      def to_hash: -> { success: true }
    end
  end
end
