module XTwitterScraper
  module Models
    type integration_list_response =
      { integrations: ::Array[XTwitterScraper::Integration] }

    class IntegrationListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor integrations: ::Array[XTwitterScraper::Integration]

      def initialize: (
        integrations: ::Array[XTwitterScraper::Integration]
      ) -> void

      def to_hash: -> { integrations: ::Array[XTwitterScraper::Integration] }
    end
  end
end
