module XTwitterScraper
  module Models
    type integration_create_params =
      {
        config: XTwitterScraper::IntegrationCreateParams::Config,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        name: String,
        type: :telegram
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class IntegrationCreateParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor config: XTwitterScraper::IntegrationCreateParams::Config

      attr_accessor event_types: ::Array[XTwitterScraper::Models::event_type]

      attr_accessor name: String

      attr_accessor type: :telegram

      def initialize: (
        config: XTwitterScraper::IntegrationCreateParams::Config,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        name: String,
        ?type: :telegram,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        config: XTwitterScraper::IntegrationCreateParams::Config,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        name: String,
        type: :telegram,
        request_options: XTwitterScraper::RequestOptions
      }

      type config = { chat_id: String }

      class Config < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor chat_id: String

        def initialize: (chat_id: String) -> void

        def to_hash: -> { chat_id: String }
      end
    end
  end
end
