module XTwitterScraper
  module Models
    type integration =
      {
        id: String,
        config: ::Hash[Symbol, top],
        created_at: Time,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        is_active: bool,
        name: String,
        type: :telegram,
        filters: ::Hash[Symbol, top],
        message_template: String,
        scope_all_monitors: bool,
        silent_push: bool
      }

    class Integration < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor config: ::Hash[Symbol, top]

      attr_accessor created_at: Time

      attr_accessor event_types: ::Array[XTwitterScraper::Models::event_type]

      attr_accessor is_active: bool

      attr_accessor name: String

      attr_accessor type: :telegram

      attr_reader filters: ::Hash[Symbol, top]?

      def filters=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader message_template: String?

      def message_template=: (String) -> String

      attr_reader scope_all_monitors: bool?

      def scope_all_monitors=: (bool) -> bool

      attr_reader silent_push: bool?

      def silent_push=: (bool) -> bool

      def initialize: (
        id: String,
        config: ::Hash[Symbol, top],
        created_at: Time,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        is_active: bool,
        name: String,
        ?filters: ::Hash[Symbol, top],
        ?message_template: String,
        ?scope_all_monitors: bool,
        ?silent_push: bool,
        ?type: :telegram
      ) -> void

      def to_hash: -> {
        id: String,
        config: ::Hash[Symbol, top],
        created_at: Time,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        is_active: bool,
        name: String,
        type: :telegram,
        filters: ::Hash[Symbol, top],
        message_template: String,
        scope_all_monitors: bool,
        silent_push: bool
      }
    end
  end
end
