module XTwitterScraper
  module Models
    type integration_create_params =
      {
        config: XTwitterScraper::IntegrationCreateParams::Config,
        event_types: ::Array[XTwitterScraper::Models::IntegrationCreateParams::event_type],
        name: String,
        type: XTwitterScraper::Models::IntegrationCreateParams::type_
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class IntegrationCreateParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor config: XTwitterScraper::IntegrationCreateParams::Config

      attr_accessor event_types: ::Array[XTwitterScraper::Models::IntegrationCreateParams::event_type]

      attr_accessor name: String

      attr_accessor type: XTwitterScraper::Models::IntegrationCreateParams::type_

      def initialize: (
        config: XTwitterScraper::IntegrationCreateParams::Config,
        event_types: ::Array[XTwitterScraper::Models::IntegrationCreateParams::event_type],
        name: String,
        type: XTwitterScraper::Models::IntegrationCreateParams::type_,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        config: XTwitterScraper::IntegrationCreateParams::Config,
        event_types: ::Array[XTwitterScraper::Models::IntegrationCreateParams::event_type],
        name: String,
        type: XTwitterScraper::Models::IntegrationCreateParams::type_,
        request_options: XTwitterScraper::RequestOptions
      }

      type config = { chat_id: String }

      class Config < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor chat_id: String

        def initialize: (chat_id: String) -> void

        def to_hash: -> { chat_id: String }
      end

      type event_type =
        :"tweet.new"
        | :"tweet.reply"
        | :"tweet.retweet"
        | :"tweet.quote"
        | :"follower.gained"
        | :"follower.lost"

      module EventType
        extend XTwitterScraper::Internal::Type::Enum

        TWEET_NEW: :"tweet.new"
        TWEET_REPLY: :"tweet.reply"
        TWEET_RETWEET: :"tweet.retweet"
        TWEET_QUOTE: :"tweet.quote"
        FOLLOWER_GAINED: :"follower.gained"
        FOLLOWER_LOST: :"follower.lost"

        def self?.values: -> ::Array[XTwitterScraper::Models::IntegrationCreateParams::event_type]
      end

      type type_ = :telegram

      module Type
        extend XTwitterScraper::Internal::Type::Enum

        TELEGRAM: :telegram

        def self?.values: -> ::Array[XTwitterScraper::Models::IntegrationCreateParams::type_]
      end
    end
  end
end
