module XTwitterScraper
  module Models
    type integration_list_deliveries_response =
      { deliveries: ::Array[XTwitterScraper::IntegrationDelivery] }

    class IntegrationListDeliveriesResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor deliveries: ::Array[XTwitterScraper::IntegrationDelivery]

      def initialize: (
        deliveries: ::Array[XTwitterScraper::IntegrationDelivery]
      ) -> void

      def to_hash: -> {
        deliveries: ::Array[XTwitterScraper::IntegrationDelivery]
      }
    end
  end
end
