module XTwitterScraper
  module Models
    type integration_list_deliveries_params =
      { id: String, limit: Integer }
      & XTwitterScraper::Internal::Type::request_parameters

    class IntegrationListDeliveriesParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        id: String,
        ?limit: Integer,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        limit: Integer,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
