module XTwitterScraper
  module Models
    type monitor_update_params =
      {
        id: String,
        event_types: ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type],
        is_active: bool
      }
      & XTwitterScraper::Internal::Type::request_parameters

    class MonitorUpdateParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader event_types: ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type]?

      def event_types=: (
        ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type]
      ) -> ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type]

      attr_reader is_active: bool?

      def is_active=: (bool) -> bool

      def initialize: (
        id: String,
        ?event_types: ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type],
        ?is_active: bool,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        event_types: ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type],
        is_active: bool,
        request_options: XTwitterScraper::RequestOptions
      }

      type event_type =
        :"tweet.new"
        | :"tweet.reply"
        | :"tweet.retweet"
        | :"tweet.quote"
        | :"follower.gained"
        | :"follower.lost"

      module EventType
        extend XTwitterScraper::Internal::Type::Enum

        TWEET_NEW: :"tweet.new"
        TWEET_REPLY: :"tweet.reply"
        TWEET_RETWEET: :"tweet.retweet"
        TWEET_QUOTE: :"tweet.quote"
        FOLLOWER_GAINED: :"follower.gained"
        FOLLOWER_LOST: :"follower.lost"

        def self?.values: -> ::Array[XTwitterScraper::Models::MonitorUpdateParams::event_type]
      end
    end
  end
end
