# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type monitor_list_response =
      { monitors: ::Array[XTwitterScraper::Monitor], total: Integer }

    class MonitorListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor monitors: ::Array[XTwitterScraper::Monitor]

      attr_accessor total: Integer

      def initialize: (
        monitors: ::Array[XTwitterScraper::Monitor],
        total: Integer
      ) -> void

      def to_hash: -> {
        monitors: ::Array[XTwitterScraper::Monitor],
        total: Integer
      }
    end
  end
end
