module XTwitterScraper
  module Models
    type monitor_deactivate_response = { success: true }

    class MonitorDeactivateResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor success: true

      def initialize: (?success: true) -> void

      def to_hash: -> { success: true }
    end
  end
end
