# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type monitor_deactivate_params =
      { id: String } & XTwitterScraper::Internal::Type::request_parameters

    class MonitorDeactivateParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
