# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type monitor_list_params =
      {  } & XTwitterScraper::Internal::Type::request_parameters

    class MonitorListParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      def initialize: (?request_options: XTwitterScraper::request_opts) -> void

      def to_hash: -> { request_options: XTwitterScraper::RequestOptions }
    end
  end
end
