# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type monitor =
      {
        id: String,
        created_at: Time,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        is_active: bool,
        next_billing_at: Time,
        username: String,
        x_user_id: String
      }

    class Monitor < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor event_types: ::Array[XTwitterScraper::Models::event_type]

      attr_accessor is_active: bool

      attr_accessor next_billing_at: Time

      attr_accessor username: String

      attr_accessor x_user_id: String

      def initialize: (
        id: String,
        created_at: Time,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        is_active: bool,
        next_billing_at: Time,
        username: String,
        x_user_id: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        event_types: ::Array[XTwitterScraper::Models::event_type],
        is_active: bool,
        next_billing_at: Time,
        username: String,
        x_user_id: String
      }
    end
  end
end
