# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type paginated_users =
      {
        has_next_page: bool,
        next_cursor: String,
        users: ::Array[XTwitterScraper::UserProfile]
      }

    class PaginatedUsers < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor has_next_page: bool

      attr_accessor next_cursor: String

      attr_accessor users: ::Array[XTwitterScraper::UserProfile]

      def initialize: (
        has_next_page: bool,
        next_cursor: String,
        users: ::Array[XTwitterScraper::UserProfile]
      ) -> void

      def to_hash: -> {
        has_next_page: bool,
        next_cursor: String,
        users: ::Array[XTwitterScraper::UserProfile]
      }
    end
  end
end
