# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type radar_item =
      {
        id: String,
        category: XTwitterScraper::Models::RadarItem::category,
        created_at: Time,
        language: String,
        metadata: XTwitterScraper::RadarItem::Metadata,
        published_at: Time,
        region: String,
        score: Float,
        source: XTwitterScraper::Models::RadarItem::source,
        source_id: String,
        title: String,
        description: String,
        image_url: String,
        url: String
      }

    class RadarItem < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor category: XTwitterScraper::Models::RadarItem::category

      attr_accessor created_at: Time

      attr_accessor language: String

      attr_accessor metadata: XTwitterScraper::RadarItem::Metadata

      attr_accessor published_at: Time

      attr_accessor region: String

      attr_accessor score: Float

      attr_accessor source: XTwitterScraper::Models::RadarItem::source

      attr_accessor source_id: String

      attr_accessor title: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader image_url: String?

      def image_url=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      def initialize: (
        id: String,
        category: XTwitterScraper::Models::RadarItem::category,
        created_at: Time,
        language: String,
        metadata: XTwitterScraper::RadarItem::Metadata,
        published_at: Time,
        region: String,
        score: Float,
        source: XTwitterScraper::Models::RadarItem::source,
        source_id: String,
        title: String,
        ?description: String,
        ?image_url: String,
        ?url: String
      ) -> void

      def to_hash: -> {
        id: String,
        category: XTwitterScraper::Models::RadarItem::category,
        created_at: Time,
        language: String,
        metadata: XTwitterScraper::RadarItem::Metadata,
        published_at: Time,
        region: String,
        score: Float,
        source: XTwitterScraper::Models::RadarItem::source,
        source_id: String,
        title: String,
        description: String,
        image_url: String,
        url: String
      }

      type category =
        :general
        | :tech
        | :dev
        | :science
        | :culture
        | :politics
        | :business
        | :entertainment

      module Category
        extend XTwitterScraper::Internal::Type::Enum

        GENERAL: :general
        TECH: :tech
        DEV: :dev
        SCIENCE: :science
        CULTURE: :culture
        POLITICS: :politics
        BUSINESS: :business
        ENTERTAINMENT: :entertainment

        def self?.values: -> ::Array[XTwitterScraper::Models::RadarItem::category]
      end

      type metadata =
        {
          author: String,
          content_url: String,
          estimated_downvotes: Integer,
          estimated_upvotes: Integer,
          number_comments: Integer,
          score: Integer,
          selftext: String,
          source_format: XTwitterScraper::Models::RadarItem::Metadata::source_format,
          subreddit: String,
          upvote_ratio: Float
        }

      class Metadata < XTwitterScraper::Internal::Type::BaseModel
        attr_reader author: String?

        def author=: (String) -> String

        attr_reader content_url: String?

        def content_url=: (String) -> String

        attr_reader estimated_downvotes: Integer?

        def estimated_downvotes=: (Integer) -> Integer

        attr_reader estimated_upvotes: Integer?

        def estimated_upvotes=: (Integer) -> Integer

        attr_reader number_comments: Integer?

        def number_comments=: (Integer) -> Integer

        attr_reader score: Integer?

        def score=: (Integer) -> Integer

        attr_reader selftext: String?

        def selftext=: (String) -> String

        attr_reader source_format: XTwitterScraper::Models::RadarItem::Metadata::source_format?

        def source_format=: (
          XTwitterScraper::Models::RadarItem::Metadata::source_format
        ) -> XTwitterScraper::Models::RadarItem::Metadata::source_format

        attr_reader subreddit: String?

        def subreddit=: (String) -> String

        attr_reader upvote_ratio: Float?

        def upvote_ratio=: (Float) -> Float

        def initialize: (
          ?author: String,
          ?content_url: String,
          ?estimated_downvotes: Integer,
          ?estimated_upvotes: Integer,
          ?number_comments: Integer,
          ?score: Integer,
          ?selftext: String,
          ?source_format: XTwitterScraper::Models::RadarItem::Metadata::source_format,
          ?subreddit: String,
          ?upvote_ratio: Float
        ) -> void

        def to_hash: -> {
          author: String,
          content_url: String,
          estimated_downvotes: Integer,
          estimated_upvotes: Integer,
          number_comments: Integer,
          score: Integer,
          selftext: String,
          source_format: XTwitterScraper::Models::RadarItem::Metadata::source_format,
          subreddit: String,
          upvote_ratio: Float
        }

        type source_format = :html | :json | :rss

        module SourceFormat
          extend XTwitterScraper::Internal::Type::Enum

          HTML: :html
          JSON: :json
          RSS: :rss

          def self?.values: -> ::Array[XTwitterScraper::Models::RadarItem::Metadata::source_format]
        end
      end

      type source =
        :github
        | :google_trends
        | :hacker_news
        | :polymarket
        | :reddit
        | :trustmrr
        | :wikipedia

      module Source
        extend XTwitterScraper::Internal::Type::Enum

        GITHUB: :github
        GOOGLE_TRENDS: :google_trends
        HACKER_NEWS: :hacker_news
        POLYMARKET: :polymarket
        REDDIT: :reddit
        TRUSTMRR: :trustmrr
        WIKIPEDIA: :wikipedia

        def self?.values: -> ::Array[XTwitterScraper::Models::RadarItem::source]
      end
    end
  end
end
