module XTwitterScraper
  module Models
    type radar_retrieve_trending_topics_response =
      { items: ::Array[XTwitterScraper::RadarItem], total: Integer }

    class RadarRetrieveTrendingTopicsResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor items: ::Array[XTwitterScraper::RadarItem]

      attr_accessor total: Integer

      def initialize: (
        items: ::Array[XTwitterScraper::RadarItem],
        total: Integer
      ) -> void

      def to_hash: -> {
        items: ::Array[XTwitterScraper::RadarItem],
        total: Integer
      }
    end
  end
end
