module XTwitterScraper
  module Models
    type radar_item =
      {
        id: String,
        category: XTwitterScraper::Models::RadarItem::category,
        created_at: Time,
        language: String,
        metadata: ::Hash[Symbol, top],
        published_at: Time,
        region: String,
        score: Float,
        source: XTwitterScraper::Models::RadarItem::source,
        source_id: String,
        title: String,
        description: String,
        image_url: String,
        url: String
      }

    class RadarItem < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor category: XTwitterScraper::Models::RadarItem::category

      attr_accessor created_at: Time

      attr_accessor language: String

      attr_accessor metadata: ::Hash[Symbol, top]

      attr_accessor published_at: Time

      attr_accessor region: String

      attr_accessor score: Float

      attr_accessor source: XTwitterScraper::Models::RadarItem::source

      attr_accessor source_id: String

      attr_accessor title: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader image_url: String?

      def image_url=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      def initialize: (
        id: String,
        category: XTwitterScraper::Models::RadarItem::category,
        created_at: Time,
        language: String,
        metadata: ::Hash[Symbol, top],
        published_at: Time,
        region: String,
        score: Float,
        source: XTwitterScraper::Models::RadarItem::source,
        source_id: String,
        title: String,
        ?description: String,
        ?image_url: String,
        ?url: String
      ) -> void

      def to_hash: -> {
        id: String,
        category: XTwitterScraper::Models::RadarItem::category,
        created_at: Time,
        language: String,
        metadata: ::Hash[Symbol, top],
        published_at: Time,
        region: String,
        score: Float,
        source: XTwitterScraper::Models::RadarItem::source,
        source_id: String,
        title: String,
        description: String,
        image_url: String,
        url: String
      }

      type category =
        :general
        | :tech
        | :dev
        | :science
        | :culture
        | :politics
        | :business
        | :entertainment

      module Category
        extend XTwitterScraper::Internal::Type::Enum

        GENERAL: :general
        TECH: :tech
        DEV: :dev
        SCIENCE: :science
        CULTURE: :culture
        POLITICS: :politics
        BUSINESS: :business
        ENTERTAINMENT: :entertainment

        def self?.values: -> ::Array[XTwitterScraper::Models::RadarItem::category]
      end

      type source =
        :github
        | :google_trends
        | :hacker_news
        | :polymarket
        | :reddit
        | :trustmrr
        | :wikipedia

      module Source
        extend XTwitterScraper::Internal::Type::Enum

        GITHUB: :github
        GOOGLE_TRENDS: :google_trends
        HACKER_NEWS: :hacker_news
        POLYMARKET: :polymarket
        REDDIT: :reddit
        TRUSTMRR: :trustmrr
        WIKIPEDIA: :wikipedia

        def self?.values: -> ::Array[XTwitterScraper::Models::RadarItem::source]
      end
    end
  end
end
