module XTwitterScraper
  module Models
    type style_list_response =
      { styles: ::Array[XTwitterScraper::StyleProfileSummary] }

    class StyleListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor styles: ::Array[XTwitterScraper::StyleProfileSummary]

      def initialize: (
        styles: ::Array[XTwitterScraper::StyleProfileSummary]
      ) -> void

      def to_hash: -> { styles: ::Array[XTwitterScraper::StyleProfileSummary] }
    end
  end
end
