# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type style_compare_response =
      {
        :style1 => XTwitterScraper::StyleProfile,
        :style2 => XTwitterScraper::StyleProfile
      }

    class StyleCompareResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor style1: XTwitterScraper::StyleProfile

      attr_accessor style2: XTwitterScraper::StyleProfile

      def initialize: (
        style1: XTwitterScraper::StyleProfile,
        style2: XTwitterScraper::StyleProfile
      ) -> void

      def to_hash: -> {
        :style1 => XTwitterScraper::StyleProfile,
        :style2 => XTwitterScraper::StyleProfile
      }
    end
  end
end
