module XTwitterScraper
  module Models
    type style_retrieve_response =
      {
        fetched_at: Time,
        is_own_account: bool,
        tweet_count: Integer,
        tweets: ::Array[XTwitterScraper::Models::StyleRetrieveResponse::Tweet],
        x_username: String
      }

    class StyleRetrieveResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor fetched_at: Time

      attr_accessor is_own_account: bool

      attr_accessor tweet_count: Integer

      attr_accessor tweets: ::Array[XTwitterScraper::Models::StyleRetrieveResponse::Tweet]

      attr_accessor x_username: String

      def initialize: (
        fetched_at: Time,
        is_own_account: bool,
        tweet_count: Integer,
        tweets: ::Array[XTwitterScraper::Models::StyleRetrieveResponse::Tweet],
        x_username: String
      ) -> void

      def to_hash: -> {
        fetched_at: Time,
        is_own_account: bool,
        tweet_count: Integer,
        tweets: ::Array[XTwitterScraper::Models::StyleRetrieveResponse::Tweet],
        x_username: String
      }

      type tweet =
        {
          id: String,
          text: String,
          author_username: String,
          created_at: String
        }

      class Tweet < XTwitterScraper::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor text: String

        attr_reader author_username: String?

        def author_username=: (String) -> String

        attr_reader created_at: String?

        def created_at=: (String) -> String

        def initialize: (
          id: String,
          text: String,
          ?author_username: String,
          ?created_at: String
        ) -> void

        def to_hash: -> {
          id: String,
          text: String,
          author_username: String,
          created_at: String
        }
      end
    end
  end
end
