module XTwitterScraper
  module Models
    type subscribe_create_response =
      {
        message: String,
        status: XTwitterScraper::Models::SubscribeCreateResponse::status,
        url: String
      }

    class SubscribeCreateResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor message: String

      attr_accessor status: XTwitterScraper::Models::SubscribeCreateResponse::status

      attr_accessor url: String

      def initialize: (
        message: String,
        status: XTwitterScraper::Models::SubscribeCreateResponse::status,
        url: String
      ) -> void

      def to_hash: -> {
        message: String,
        status: XTwitterScraper::Models::SubscribeCreateResponse::status,
        url: String
      }

      type status = :checkout_created | :already_subscribed | :payment_issue

      module Status
        extend XTwitterScraper::Internal::Type::Enum

        CHECKOUT_CREATED: :checkout_created
        ALREADY_SUBSCRIBED: :already_subscribed
        PAYMENT_ISSUE: :payment_issue

        def self?.values: -> ::Array[XTwitterScraper::Models::SubscribeCreateResponse::status]
      end
    end
  end
end
