# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type webhook_list_response = { webhooks: ::Array[XTwitterScraper::Webhook] }

    class WebhookListResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor webhooks: ::Array[XTwitterScraper::Webhook]

      def initialize: (webhooks: ::Array[XTwitterScraper::Webhook]) -> void

      def to_hash: -> { webhooks: ::Array[XTwitterScraper::Webhook] }
    end
  end
end
