module XTwitterScraper
  module Models
    type webhook_list_deliveries_response =
      { deliveries: ::Array[XTwitterScraper::Delivery] }

    class WebhookListDeliveriesResponse < XTwitterScraper::Internal::Type::BaseModel
      attr_accessor deliveries: ::Array[XTwitterScraper::Delivery]

      def initialize: (deliveries: ::Array[XTwitterScraper::Delivery]) -> void

      def to_hash: -> { deliveries: ::Array[XTwitterScraper::Delivery] }
    end
  end
end
