# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Models
    type x_get_trends_params =
      { count: Integer, woeid: Integer }
      & XTwitterScraper::Internal::Type::request_parameters

    class XGetTrendsParams < XTwitterScraper::Internal::Type::BaseModel
      extend XTwitterScraper::Internal::Type::RequestParameters::Converter
      include XTwitterScraper::Internal::Type::RequestParameters

      attr_reader count: Integer?

      def count=: (Integer) -> Integer

      attr_reader woeid: Integer?

      def woeid=: (Integer) -> Integer

      def initialize: (
        ?count: Integer,
        ?woeid: Integer,
        ?request_options: XTwitterScraper::request_opts
      ) -> void

      def to_hash: -> {
        count: Integer,
        woeid: Integer,
        request_options: XTwitterScraper::RequestOptions
      }
    end
  end
end
