# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Internal
    module Type
      module Converter
        extend XTwitterScraper::Internal::Util::SorbetRuntimeSupport

        type input = XTwitterScraper::Internal::Type::Converter | Class

        type coerce_state =
          {
            translate_names: bool,
            strictness: bool,
            exactness: { yes: Integer, no: Integer, maybe: Integer },
            error: Class,
            branched: Integer
          }

        type dump_state = { can_retry: bool }

        def coerce: (
          top value,
          state: XTwitterScraper::Internal::Type::Converter::coerce_state
        ) -> top

        def dump: (
          top value,
          state: XTwitterScraper::Internal::Type::Converter::dump_state
        ) -> top

        def inspect: (?depth: Integer) -> String

        def self.type_info: (
          {
            const: (nil | bool | Integer | Float | Symbol)?,
            enum: ^-> XTwitterScraper::Internal::Type::Converter::input?,
            union: ^-> XTwitterScraper::Internal::Type::Converter::input?
          }
          | ^-> XTwitterScraper::Internal::Type::Converter::input
          | XTwitterScraper::Internal::Type::Converter::input spec
        ) -> (^-> top)

        def self.meta_info: (
          {
            const: (nil | bool | Integer | Float | Symbol)?,
            enum: ^-> XTwitterScraper::Internal::Type::Converter::input?,
            union: ^-> XTwitterScraper::Internal::Type::Converter::input?
          }
          | ^-> XTwitterScraper::Internal::Type::Converter::input
          | XTwitterScraper::Internal::Type::Converter::input type_info,
          {
            const: (nil | bool | Integer | Float | Symbol)?,
            enum: ^-> XTwitterScraper::Internal::Type::Converter::input?,
            union: ^-> XTwitterScraper::Internal::Type::Converter::input?
          }
          | ^-> XTwitterScraper::Internal::Type::Converter::input
          | XTwitterScraper::Internal::Type::Converter::input spec
        ) -> ::Hash[Symbol, top]

        def self.new_coerce_state: (
          ?translate_names: bool
        ) -> XTwitterScraper::Internal::Type::Converter::coerce_state

        def self.coerce: (
          XTwitterScraper::Internal::Type::Converter::input target,
          top value,
          ?state: XTwitterScraper::Internal::Type::Converter::coerce_state
        ) -> top

        def self.dump: (
          XTwitterScraper::Internal::Type::Converter::input target,
          top value,
          ?state: XTwitterScraper::Internal::Type::Converter::dump_state
        ) -> top

        def self.inspect: (top target, depth: Integer) -> String
      end
    end
  end
end
