# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

module XTwitterScraper
  module Internal
    module Type
      module Enum
        include XTwitterScraper::Internal::Type::Converter
        include XTwitterScraper::Internal::Util::SorbetRuntimeSupport

        def self.values: -> ::Array[(nil | bool | Integer | Float | Symbol)]

        def ===: (top other) -> bool

        def ==: (top other) -> bool

        def hash: -> Integer

        def coerce: (
          String | Symbol | top value,
          state: XTwitterScraper::Internal::Type::Converter::coerce_state
        ) -> (Symbol | top)

        def dump: (
          Symbol | top value,
          state: XTwitterScraper::Internal::Type::Converter::dump_state
        ) -> (Symbol | top)

        def to_sorbet_type: -> top

        def inspect: (?depth: Integer) -> String
      end
    end
  end
end
